speak("Owen", "I don't suppose either of you have seen the rabbit yet.")
speak("Tess", "No.")
speak("Owen", "Figures. It must've gotten downstairs. Hopefully no one kills it because it's been exposed to N9.")
speak("Lia", "Animals can carry it?")
speak("Owen", "No idea. It's not a well-understood disease, which is surprising given how devastating it could be if an outbreak became a full-fledged epidemic.")
speak("Owen", "If someone told me my pet could be contaminated... Well, I wouldn't take any chances.")
speak("Lia", "That's horrible.")
speak("Owen", "You haven't shown symptoms yet. The older you get, the worse it becomes. Have you seen what happens to infected adults?")
speak("Lia", "No...")
speak("Owen", "You grew up really sheltered, didn't you?")
speak("Owen", "The point is, there's a reason we're all locked up in here. We're contagious.")
speak("Tess", "You can ease up a bit. She's been here less than a day.")
speak("Owen", "Oh, right, Tess. I need to talk to you. I might have an idea about Cecily. But...")
speak("Owen", "Never mind. Meet me tonight at the usual spot and we can talk when there are less ears around.")
