speak("Nadine", "Hey Tess! And ummm...")
speak("Lia", "It's - ")
speak("Nadine", "Lia! I'm right, aren't I?")
speak("Lia", "Yeah. That's it.")
speak("Tess", "Good job, Nadine.")
speak("Nadine", "Haha, don't say it's a good job until I've found that little bunny. Joey's gonna be devastated if we don't get Connie back.")
speak("Lia", "We'll find her.")
speak("Nadine", "I like you. Just showed up today and still pitching in.")
