speak("Dr. Cooper", "Hey Tess! Who's this fresh face?")
speak("Tess", "Dr. Cooper, this is Lia. The new patient.")
speak("Lia", "N-nice to meet you Dr. Cooper.")
speak("Dr. Cooper", "Just Cal is fine. And that goes for you too, Tess, for the thousandth time.")
speak("Tess", "I'll keep that in mind, Dr. Cooper.")
speak("Dr. Cooper", "Sheesh...")
speak("Dr. Cooper", "Anyways Lia, I'm one of the doctors assigned to this ward. Well, more like a researcher than a doctor.")
speak("Dr. Cooper", "But I'm sure we'll be getting to know each other soon!")
speak("Dr. Cooper", "I'm expecting some result in so I gotta run, but, see you at 4:00, right Tess?")
speak("Tess", "Right.")
speak("Dr. Cooper", "Seeya!")
