speak("Tess", "Hi. I'm Tess. Patient #2876.")
speak("Lia", "I-I'm Lia.")
speak("Tess", "Are you doing alright?")
speak("Lia", "Just a bit nervous.")
speak("Tess", "That's alright. You're doing fine.")
speak("Tess", "Here's your half of the room there. I'll clear out my old roommate's things later, sorry about that.")
speak("Lia", "So you really can't talk?")
speak("Tess", "I've forgotten how.")
speak("Lia", "Is... Is that because of NEURAL-9?")
speak("Tess", "N9. Yeah.")
speak("Tess", "It affects everyone differently. If you're here, you must've tested positive too, right?")
speak("Lia", "I've been positive half my life, but... I don't really get the details.")
speak("Tess", "It's not understood how it works.")
speak("Tess", "A new epidemic that degrades memory. Always fatal. No cure. Spreads with eye contact.")
speak("Lia", "I'm used to being blindfolded. Is it really alright?")
speak("Tess", "Ward #6 is a dedicated N9 ward. All patients are positive, so we can uncover our eyes here, and the doctors wear protection.")
speak("Tess", "Maybe when the researchers here find a cure, we can go free in the outside world again.")
speak("Tess", "But until then, don't expect to be able to leave the ward.")
speak("Lia", "A-alright...")
speak("Tess", "Do you have symptoms? Forgetting things?")
speak("Lia", "No. Not yet, I guess.")
speak("Tess", "It happens to everyone slightly differently.")
speak("Tess", "But don't worry. Everyone here is about our age, and going through the same thing. We have to stick together.")
speak("Lia", "Y-yeah...")
speak("Tess", "Here, follow me and I can introduce you to everyone.")
