speak("Tess", "What's going on?")
speak("Owen", "Joey's throwing a fit.")
speak("Nadine", "Hey, calm down, calm down. Blow your nose.")
speak("Joey", "Someone must've left the hatch open! She could be anywhere!")
speak("Lia", "Tess, it's the rabbit. I think she got loose.")
speak("Owen", "That's the gist of it. Probably the thing made it to another floor, and it's not like we're allowed off this one.")
speak("Joey", "What do we do?")
speak("Tess", "We'll look for Connie in Ward #6. Dr. Cooper can check the other floors. If we all look, I'm sure we can find her.")
speak("Joey", "Okay. Thanks Tess. I don't know what I'd do without Connie.")
speak("Nadine", "I'll start here in the common room. Who's gonna talk to the docs?")
speak("Tess", "I'll do it.")
speak("Owen", "That's probably a good idea. Everyone else, start with your own room, and then we can cover the other spots.")
speak("Lia", "Tess, um... Can I come with you?")
speak("Tess", "I guess.")
speak("Lia", "I just don't want to get lost.")
