speak("Dr. Gray", "Tess. I've been looking for you.")
speak("Tess", "Hello Dr. Gray.")
speak("Dr. Gray", "Are any of your roommate's belongings still in your room?")
speak("Tess", "Some.")
speak("Dr. Gray", "Clear them out immediately.")
speak("Dr. Gray", "I would like you to meet, ahem, patient #2902. Your name again, please?")
speak("Lia", "It's Lia, Miss.")
speak("Dr. Gray", "Thank you, Lia. Please address me as Doctor in the future.")
speak("Dr. Gray", "Tess, patient #2902 is your new roommate, effective immediately.")
speak("Dr. Gray", "Please show them around then and introduce them to other patients.")
speak("Dr. Gray", "Thank you. And please remember your checkup with Dr. Cooper at 4:00. Have a good day.")
speak("Lia", "I, um... Can you talk?")
speak("Tess", "No. Sorry, you'll have to read what I'm typing on the screen.")
speak("Tess", "Come on in and I can show you around.")
