speak("Owen", "Oh. Tess. I was hoping I'd run into you. We need to - ")
speak("Owen", "Who's this?")
speak("Tess", "This is Lia. She'll be my new roommate.")
speak("Lia", "H-hello.")
speak("Owen", "Owen. Great to meet you. I'm thrilled.")
speak("Tess", "Don't be mean.")
speak("Owen", "If you've got a new roommate, that means they're giving up on Cecily.")
speak("Tess", "Not necessarily. She could still come back from... wherever she went.")
speak("Owen", "But the doctors don't think it's nicely. And it's clear they're not telling us the whole truth about her.")
speak("Tess", "Sorry, Lia. Cecily was my old roommate.")
speak("Lia", "Then she um... She died?")
speak("Owen", "She was only 18. N9 shouldn't have been fatal to her for another few years.")
speak("Owen", "She's alive out there somewhere. I know it.")
speak("Owen", "...I should apologize, Lia. I forgot none of this concerns you.")
speak("Lia", "It's fine.")
speak("Owen", "Well, welcome to Ward #6. I'm sincerely saddened that you had to come here, but none of us have any choice.")
speak("Owen", "If you want some advice, keep your ears open, and don't take everything the doctors say at face value.")
speak("Owen", "I think with Cecily gone, I've been here the longest now, so if you've got any questions, you know where to find me.")
speak("Lia", "Um, could I ask a question?")
speak("Owen", "If it's one I can answer.")
speak("Lia", "You play the piano?")
speak("Owen", "I won the Ettole Internationale at 14, and I was runner-up for the Brahms prize the year before that.")
speak("Lia", "I love music. Maybe some time I could listen - ")
speak("Owen", "No.")
speak("Owen", "If you two could leave now, I'm getting tired.")
speak("Lia", "S-sorry...")


speak("Tess", "Don't worry about Owen. He can be a bit touchy but he's an okay guy.")
speak("Lia", "I hope I didn't make him mad?")
speak("Tess", "He's a nerd for classical music, but don't bring up his playing. It's... not what it used to be.")
speak("Lia", "N9?")
speak("Tess", "N9.")
