speak("Tess", "Excuse me Dr. Gray.")
speak("Dr. Gray", "Yes?")
speak("Tess", "Do you know where Dr. Cooper is?")
speak("Dr. Gray", "I can relay a message.")
speak("Tess", "The ward pet got free. We're looking for it and thought he could help.")
speak("Dr. Gray", "Dr. Cooper isn't paid to help you with things like that.")
speak("Dr. Gray", "He may have low personal standards, but he's top-flight professional at the top of this field, and I won't have him interrupted.")
speak("Tess", "If there's a rabbit found in the rest of the hospital, could you let us know then?")
speak("Dr. Gray", "If I'm in the area.")
speak("Dr. Gray", "Frankly a pet in a N9 ward is a terrible idea, around impressionable children...")
speak("Dr. Gray", "You can thank your Dr. Cooper's whimsy for that... Of course it was never going to end well...")
