speak("Tess", "Hi Joey.")
speak("Joey", "Oh, hi Tess. Did you come to play with Connie?")
speak("Tess", "Actually I have someone I want you to meet. This is Lia. She's new.")
speak("Joey", "Oh erm, hi.")
speak("Tess", "You should tell Lia your name.")
speak("Joey", "It's Joey.")
speak("Lia", "Hi Joey. It's nice to meet you.")
speak("Joey", "Do you want to meet Connie? She lives here too.")
speak("Lia", "Sure.")
speak("Joey", "Connie, say hi.")
speak("Connie", "...")
speak("Joey", "She's not good with strangers.")
speak("Lia", "She's a... shy rabbit?")
speak("Joey", "Sure but she's friendly when she gets to know you. She's my best friend in the world.")
speak("Joey", "You're number two Tess. Don't worry. Or maybe Nadine is. It switches. But it definitely isn't Owen.")
speak("Joey", "Owen doesn't like Connie so he's not my friend either. Watch out for him.")
speak("Lia", "O-okay.")
speak("Joey", "So what happened to your face?")
speak("Tess", "Don't be rude, Joey.")
speak("Lia", "It's alright...")
speak("Lia", "Everyone knows the disease spread through eye contact, so um, I was attacked when I was kid.")
speak("Lia", "They found out I had Neural-9 and um, tried to blind me with acid. So I couldn't spread it.")
speak("Joey", "Did it work?")
speak("Lia", "I can still see. But, that's when it was decided that I'd come to Ward #6, after that.")
speak("Joey", "I'm new here too. If you're ever scared or sad, you can come find Connie. She'll be right here.")
speak("Lia", "Thanks.")
