pathEvent('d1_target0')

speak("Dr. Gray", "Tess. I've been looking for you.", 'd1_gray0')
face('hero', 'EAST')
speak("Tess", "Hello Dr. Gray.")
face('d1_lia0', 'WEST')
speak("Dr. Gray", "A question...", 'd1_gray0')
speak("Dr. Gray", "Are any of your roommate's belongings still in your room?", 'd1_gray0')
speak("Tess", "Some.")
speak("Dr. Gray", "Clear them out immediately. I have some news.", 'd1_gray0')
speak("Dr. Gray", "I would like you to meet, ahem, patient #2902. Your name again, please?", 'd1_gray0')
face('d1_lia0', 'SOUTH')
speak("Lia", "It's Lia, ma'am.", 'd1_lia0')
speak("Dr. Gray", "Thank you, Lia. Please address me as Doctor in the future.", 'd1_gray0')
speak("Dr. Gray", "Tess, patient #2902 is your new roommate, effective immediately.", 'd1_gray0')
speak("Dr. Gray", "Please show them around then and introduce them to other patients.", 'd1_gray0')
speak("Tess", "Understood.")
speak("Dr. Gray", "Good. And please remember your checkup with Dr. Cooper at 4:00.", 'd1_gray0')
speak("Dr. Gray", "Take care.", 'd1_gray0')
walk('d1_gray0', 10, 'EAST', false)
face('d1_lia0', 'EAST')
wait(0.8)
pathEvent('d1_target1')
face('hero', 'EAST')
face('d1_lia0', 'WEST')
speak("Tess", "Hi. Sorry about Dr. Gray. She's always a bit on edge.")
speak("Lia", "I, um... Can you not talk?", 'd1_lia0')
speak("Tess", "No. Sorry, you'll have to read what I'm typing on the device.")
speak("Tess", "Come on in and I can show you around.")

targetTele('RoomYours', 'd1_target0')
setSwitch('day1_01_gray', true)
