speak("Nadine", "Hey there! Er, it's uh, errr...")
speak("Tess", "It's Tess.")
speak("Nadine", "Hey Tess. Right! And you, er, if you're with Tess, you must be Cecily?")
speak("Lia", "I'm um, Lia. I'm going to be roommates with Tess.")
speak("Nadine", "Ohh, okay. So I haven't met you before. Exciting!")
speak("Nadine", "Sorry if you have to introduce yourself again. I'm Nadine, and I'm really bad with names. And faces.")
speak("Lia", "I don't mind.")
speak("Nadine", "And if I could find my camera, I'd love to take your picture.")
speak("Lia", "You're a photographer? I-I'm not really good-looking...")
speak("Nadine", "Oh, no haha, I just take photos for my flashcards. If you're gonna be joining Ward #6, I want to remember you.")
speak("Lia", "Flashcards?")
speak("Nadine", "Here. See?")
card('flashcards')
speak("Lia", "That's... um...")
speak("Nadine", "My family's going to visit any day now, so I need to be prepared.")
speak("Nadine", "Do you have any symptoms yet? N9 kind of sucks.")
speak("Lia", "No real symptoms... I don't think.")
speak("Nadine", "Well if you're really bored, come practice with me sometime. I'm either here or in the common room.")
speak("Nadine", "And stick close to Tess. She's great!")
speak("Tess", "Thanks Nadine. Take care.")
