speak("Nadine", "Tess! Did you find her?")
speak("Nadine", "I've been looking in here for ages but I didn't see anything. How'd you know right where to - ")
speak("Nadine", "Connie?")
card('dead_rabbit')
speak("Nadine", "Aaagh!")
speak("Tess", "You have to keep it together. For Joey.")
speak("Nadine", "But... the poor thing. What happened to her?")
speak("Tess", "I have no idea. She doesn't look like she has any broken bones or wounds or things like that.")
speak("Tess", "Except for her eyes.")
speak("Nadine", "Except for the eyes...")
speak("Tess", "We can't let Joey see her like this. Maybe there's a way to clean the blood off.")
speak("Nadine", "Should we find one of the doctors?")
speak("Tess", "I don't know. There's not much we can do on our own.")
speak("Nadine", "Poor Connie...")
