speak("Lia", "Oh. You're back. Hi Tess.")
speak("Tess", "Hello.")
speak("Lia", "I wish I could've been more help looking for Connie...")
speak("Tess", "You did fine.")
speak("Lia", "The atmosphere here feels so different from yesterday. No one really wants to see me.")
speak("Tess", "Everyone is processing, is all. We've had Connie for as long as I can remember.")
speak("Tess", "By the way, you did only show up here yesterday, correct?")
speak("Lia", "T-that's right.")
speak("Tess", "Thank you. Sorry, sometimes with N9, it pays to double check.")
speak("Lia", "Are you going to be sneaking out again tonight?")
speak("Tess", "I'm not sure.")
speak("Lia", "Oh.")
speak("Tess", "But if you could cover for me again I'd be grateful.")
speak("Lia", "I will. I'll do whatever I can.")
speak("Tess", "Goodnight.")
