speak("Dr. Gray", "I heard you found the rabbit.")
speak("Tess", "Yes, but, she's dead.")
speak("Dr. Gray", "Then please hand over the corpse.")
speak("Tess", "It's in the storage room.")
speak("Dr. Gray", "I suppose the rabbit's death was inevitable, but that doesn't make the cleanup any more enviable.")
speak("Tess", "She was fine last time...")
speak("Dr. Gray", "Eventually everything dies and is forgotten.")
speak("Tess", "Dr. Gray, do you remember us searching for Connie yesterday?")
speak("Dr. Gray", "...")
speak("Dr. Gray", "I'll dispose of the body. Please try not to upset the others.")
