speak("Owen", "Tess. Are you alright?")
speak("Tess", "I'll be fine. I'm more worried about Joey.")
speak("Owen", "He's young. He'll forget eventually. I'm more worried about you.")
speak("Tess", "Me? What about me?")
speak("Owen", "You found Connie exactly where you predicted, didn't you?")
speak("Tess", "I didn't predict it. It's where I found her yesterday.")
speak("Owen", "Right. The deja-vu, or whatever it was.")
speak("Tess", "It really happened.")
speak("Owen", "This is going to sound ridiculous, but...")
speak("Owen", "Are you familiar with the idea of a false memory?")
speak("Tess", "It's not a false memory. It's exactly what happened yesterday.")
speak("Tess", "I found Connie there again. Doesn't that prove it?")
speak("Owen", "You're telling me you found Connie dead yesterday, she came back to life, then ran away, then died again in the same spot?")
speak("Tess", "No. She was alive yesterday.")
speak("Owen", "Oh. Then...")
speak("Owen", "I don't like this at all.")
speak("Owen", "Of course it's a false memory. Not a random one.")
speak("Owen", "Someone killed Connie, dumped her, then waited to see if you'd follow this false memory to the spot.")
speak("Tess", "They didn't need to hurt the rabbit. They could've just seen if I searched the same place, without kiling her.")
speak("Owen", "No. No you're right, that doesn't make sense.")
speak("Owen", "But it has to be a fake memory! Or a lucky hunch and a delusion. You're not delusional are you?")
speak("Tess", "I think one of the signs of being delusional is you don't recognize that you're delusional.")
speak("Owen", "Ha. Well, you're as level-headed as ever Tess, so, I guess you're not delusional.")
speak("Owen", "Then what gives?")
speak("Tess", "Everyone here is N9 positive. It seems unlikely, but maybe everyone else really did forget.")
speak("Owen", "That would be a huge coincidence. Or else there's some specific pattern to the memories we lose...")
speak("Owen", "Or maybe -- how many days ago do you remember this taking place?")
speak("Tess", "It was yesterday.")
speak("Owen", "Maybe it happened months ago and you just forget that that much time has passed.")
speak("Tess", "It happened on Lia's first day here.")
speak("Owen", "Hm... How many days has it been since she arrived now?")
speak("Tess", "One. One day.")
speak("Owen", "You sound convinced of that, but I can't say for sure. She's new, but...")
speak("Tess", "It's been one day. Ask anyone. Ask her.")
speak("Owen", "Listen, meet me tonight, right here. Bring the key.")
speak("Tess", "Alright?")
speak("Owen", "I have a really, really bad feeling. It's almost like...")
speak("Owen", "You ever miss a step on the stairs? It's like I missed a step and then looked down, and there's only a cliff, and...")
speak("Owen", "It's just crazy thoughts.")
speak("Tess", "What's worrying you?")
speak("Owen", "It'd make sense if... Like what if I never was any good at the piano.")
speak("Owen", "It's just deja vu. I've played this before. I used to be good at this.")
speak("Owen", "Maybe I didn't forget. I just have this stupid, sure feeling of something that never happened.")
speak("Tess", "That's a lot of what-ifs.")
speak("Owen", "You're right. I'm overthinking it.")
speak("Owen", "Let's go over things tonight. I want to see that lab you were talking about.")
speak("Tess", "It's a plan.")
