speak("Dr. Cooper", "Oh, Tess. I heard about Connie.")
speak("Tess", "It's unfortunate.")
speak("Dr. Cooper", "Yeah, I...")
speak("Dr. Cooper", "I'm so sorry.")
speak("Tess", "Sorry for what?")
speak("Dr. Cooper", "It's an expression of empathy.")
speak("Tess", "It's Joey that's torn up. Not me.")
speak("Tess", "Do you remember searching for Connie yesterday?")
speak("Dr. Cooper", "I wish I could give you the answer you wanted, Tess.")
speak("Tess", "I just want a yes or no.")
speak("Dr. Cooper", "I'm sorry.")
