speak("Tess", "Now what?")
speak("Owen", "Joey's throwing a fit.")
speak("Nadine", "Hey, calm down, calm down. Blow your nose.")
speak("Tess", "Don't tell me Connie got out again.")
speak("Owen", "That's it exactly.")
speak("Joey", "Someone must've left the hatch open! She could be anywhere!")
speak("Tess", "You need to be more careful. How could she have gotten out again?")
speak("Nadine", "Connie's been loose before?")
speak("Joey", "I'd never let Connie out of this room. When she's out of her hutch, she's always with me.")
speak("Tess", "This doesn't seem familiar to anyone else?")
speak("Owen", "No. Joey's a brat but he always takes care of the rabbit.")
speak("Owen", "I hope she didn't make it to another floor... We'd have no way to get her back.")
speak("Tess", "Nadine. Are they pulling a prank?")
speak("Nadine", "Huh? I don't think so, Tess.")
speak("Joey", "What should we do?")
speak("Owen", "Maybe Tess can talk to Dr. Cooper and see about searching the other floors?")
speak("Tess", "I have an idea where we might find her.")
speak("Owen", "Okay?")
speak("Owen", "What's everyone standing around for? We should be searching.")
speak("Joey", "Right! I'll start with my room.")
speak("Joey", "...I don't know what I'd do without Connie.")
speak("Nadine", "I'll start here in the common room. Who's gonna talk to the docs?")
speak("Tess", "I'll do it.")
speak("Owen", "That's probably a good idea. Everyone else, start with your own room, and then we can cover the other spots.")
speak("Lia", "Tess, um... Can I come with you?")
speak("Tess", "Stay here and look over the common room again. I have somewhere I need to check.")
speak("Lia", "Uhm... Alright.")
