speak("Owen", "Any luck last night?")
speak("Tess", "The stairs don't really go anywhere. They lead to the research lab attached to the ward, not the outside world.")
speak("Owen", "Interesting.")
speak("Owen", "How much do you know about Allsaints Hospital?")
speak("Tess", "It's a pediatric hospital, for kids and young adults. It has twelve deparments and was founded in - ")
speak("Owen", "No, never mind, stop typing. You're just copying verbatim what you've read off their pamphlets.")
speak("Owen", "What if this wasn't a hospital, but just one ward? Ward #6 and a lab. Why else would you have a staircase like that?")
speak("Tess", "Maybe they expect you to use the elevator.")
speak("Owen", "Ugh. Never mind. But the point is, it's a dead end, and not a way out...")
speak("Tess", "Not necessarily. I didn't get to finish exploring.")
speak("Owen", "It's that big?")
speak("Tess", "No.")
speak("Tess", "I got caught.")
speak("Owen", "You what? Ugh, by all - ")
speak("Nadine", "Hey, what're you guys up to?")
speak("Owen", "Nothing.")
speak("Nadine", "You're such a bad liar. You're over here whispering to Tess about something, hmmm?")
speak("Owen", "Never mind.")
speak("Tess", "I've got my checkup with Dr. Cooper now anyway. Talk later.")
