if getSwitch('day2_09_post_owen') then
    speak("Owen", "Let's go over things tonight. I want to see that lab you were talking about.", 'd2_owen4')
    return
end

speak("Owen", "Tess. Are you alright?", 'd2_owen4')
speak("Tess", "I'll be fine. I'm more worried about Joey.")
speak("Owen", "He's young. He'll forget eventually. I'm more worried about you.", 'd2_owen4')
speak("Tess", "Me? What about me?")
speak("Owen", "You found Connie exactly where you predicted, didn't you?", 'd2_owen4')
wait(.8)
speak("Tess", "I didn't predict it. It's where I found her yesterday.")
speak("Owen", "Right. The deja-vu, or whatever it was.", 'd2_owen4')
speak("Tess", "It really happened.")
face('d2_owen4', 'WEST')
speak("Owen", "This is going to sound ridiculous, but...", 'd2_owen4')
faceOther('d2_owen4', 'hero')
speak("Owen", "Are you familiar with the idea of a false memory?", 'd2_owen4')
speak("Tess", "It's not a false memory. It's exactly what happened yesterday.")
speak("Tess", "I found Connie, right there, for a second time. Doesn't that prove it?")
speak("Owen", "You're telling me you found Connie dead yesterday...", 'd2_owen4')
speak("Owen", "And she's since come back to life, run away again, then gone and died in the same spot?", 'd2_owen4')
speak("Owen", "Pardon if that stretches my disbelief.", 'd2_owen4')
speak("Tess", "No. She was alive yesterday.")
speak("Owen", "Oh. Then...", 'd2_owen4')
wait(.6)
speak("Owen", "I don't like this at all.", 'd2_owen4')
walk('d2_owen4', 2, 'SOUTH')
faceTo('d2_owen4')
speak("Owen", "Of course, it's still a false memory. It's just not a random one.", 'd2_owen4')
faceOther('d2_owen4', 'hero')
speak("Owen", "Someone killed Connie, dumped her, then waited to see if you'd follow this false memory to the spot.", 'd2_owen4')
speak("Tess", "They didn't need to hurt the rabbit. They could've just seen if I searched the same place. Why kill her?", 'd2_owen4')
speak("Owen", "No. No you're right, that doesn't make sense.", 'd2_owen4')
walk('d2_owen4', 1, 'NORTH')
speak("Owen", "But it has to be a fake memory! Or a lucky hunch and a delusion.", 'd2_owen4')
faceTo('d2_owen4', 'hero')
speak("Owen", "You're not delusional are you?", 'd2_owen4')
speak("Tess", "I think by definition if you're delusional, you don't recognize that you're delusional.")
speak("Owen", "Ha. Well, you're as level-headed as ever Tess, so, I guess you're not delusional.", 'd2_owen4')
wait(.7)
speak("Owen", "So then... what gives?", 'd2_owen4')
speak("Tess", "Everyone here is N9 positive. It seems unlikely, but maybe everyone else really did forget.")
speak("Owen", "That would be a huge coincidence. Or else there's some specific pattern to the memories we lose...", 'd2_owen4')
wait(.4)
speak("Owen", "Or maybe -- how many days ago do you remember this taking place?", 'd2_owen4')
speak("Tess", "It was yesterday.")
speak("Owen", "Maybe it happened months ago and you just forget that that much time has passed.", 'd2_owen4')
speak("Tess", "It happened on Lia's first day here.")
speak("Owen", "Hm... How many days has it been since she arrived now?", 'd2_owen4')
speak("Tess", "One. One day.")
speak("Owen", "You sound convinced of that, but I can't say for sure. She's new, but...", 'd2_owen4')
speak("Tess", "It's been one day. Ask anyone. Ask her.")
faceTo('d2_owen4', 'hero')
wait(.7)
speak("Owen", "Listen, meet me tonight, right here. Bring the key.", 'd2_owen4')
speak("Tess", "Alright?")
speak("Owen", "I have a really, really bad feeling. It's almost like...", 'd2_owen4')
wait(.7)
face('d2_owen4', 'WEST')
speak("Owen", "You ever miss a step on the stairs?", 'd2_owen4')
speak("Owen", "It's like I missed a step and then looked down, and there's only a cliff, and...", 'd2_owen4')
speak("Owen", "It's just crazy thoughts.", 'd2_owen4')
speak("Tess", "What's worrying you?")
faceOther('d2_owen4', 'hero')
speak("Owen", "It'd make sense if... Like what if I actually wasn't ever any good at the piano.", 'd2_owen4')
speak("Owen", "It's just deja vu. My brain says I played it before. My brain lies and says I used to be good at this.", 'd2_owen4')
speak("Owen", "Maybe I didn't forget. I just have this stupid, sure feeling of something that never happened.", 'd2_owen4')
speak("Tess", "That's a lot of what-ifs.")
speak("Owen", "You're right. I'm overthinking it.", 'd2_owen4')
speak("Owen", "Let's go over things tonight. I want to see that lab you were talking about.", 'd2_owen4')
speak("Tess", "It's a plan.")

setSwitch('day2_09_post_owen', true)
