faceTo('d2_owen1')
speak("Tess", "Now what?")
faceOther('d2_owen1', 'hero')
speak("Owen", "Joey's throwing a fit.", 'd2_owen1')
faceTo('d2_joey1')
faceOther('d2_owen1', 'd2_joey1')
speak("Nadine", "Hey, calm down, calm down. Blow your nose.", 'd2_nadine1')
speak("Tess", "Don't tell me Connie got out again.")
speak("Owen", "That's it exactly.", 'd2_owen1')
faceOther('d2_joey1', 'hero')
faceOther('d2_nadine1', 'hero')
speak("Joey", "Someone must've left the hatch open! She could be anywhere!", 'd2_joey1')
speak("Tess", "You need to be more careful. How could she have gotten out again?")
speak("Nadine", "Connie's been loose before?", 'd2_nadine1')
speak("Joey", "I'd never let Connie out of this room. When she's out of her hutch, she's always with me.", 'd2_joey1')
wait(.4)
faceTo('d2_nadine1')
wait(.4)
faceTo('d2_owen1')
wait(.4)
speak("Tess", "This doesn't seem familiar to anyone else?")
speak("Owen", "No. Joey may be a brat, but he always does take good care of the rabbit.", 'd2_owen1')
speak("Owen", "I hope she didn't make it to another floor... We'd have no way to get her back.", 'd2_owen1')
wait(.7)
faceTo('d2_nadine1')
speak("Tess", "Nadine. Are they pulling a prank?")
speak("Nadine", "Huh? I don't think so, Tess.", 'd2_nadine1')
speak("Joey", "What should we do?", 'd2_joey1')
speak("Owen", "Maybe Tess can talk to Dr. Cooper and see about searching the other floors?", 'd2_owen1')
speak("Tess", "I have an idea where we might find her.")
faceOther('d2_owen1', 'hero')
speak("Owen", "Good for you? Why don't you check there then?", 'd2_owen1')
faceOther('d2_owen1', 'd2_joey1')
faceOther('d2_lia1', 'd2_owen1')
speak("Owen", "What's everyone standing around for? We should be searching.", 'd2_owen1')
speak("Joey", "Right! I'll double-check this room.", 'd2_joey1')
speak("Joey", "...I don't know what I'd do without Connie.", 'd2_joey1')
faceOther('d2_lia1', 'd2_joey1')
speak("Nadine", "We'll find her for sure.", 'd2_nadine1')
faceOther('d2_lia1', 'd2_owen1')
speak("Nadine", "Who's gonna talk to the docs?", 'd2_nadine1')
faceOther('d2_owen1', 'hero')
faceOther('d2_nadine1', 'hero')
speak("Tess", "I'll do it.")
speak("Owen", "That's probably a good idea.", 'd2_owen1')
walk('d2_owen1', 1, 'WEST')
speak("Owen", "Everyone else, start with your own room, and we'll cover the rest of the floor later.", 'd2_owen1')
faceOther('d2_lia1', 'hero')
faceTo('d2_lia1')
speak("Lia", "Tess, um... Can I come with you?", 'd2_lia1')
speak("Tess", "Stay here and look over the common room again. I have somewhere I need to look.")
speak("Lia", "Uhm... Alright.", 'd2_lia1')

fade('black')
setSwitch('day2_03_meeting', true)
fade('normal')
