speak("Joey", "...")
speak("Lia", "Joey?")
speak("Joey", "...")
speak("Lia", "Joey, it's me. Lia.")
speak("Joey", "Where are you...?")
speak("Lia", "I'm right here, Joey.")
speak("Joey", "Where did you go...?")
speak("Lia", "Okay Joey.")
speak("Joey", "Where...")
speak("Lia", "T-this is Joey. His case is kind of pretty far along, but when he's all there, he's a good kid.")
speak("Lia", "Joey? Joey can you say hi to Tess?")
speak("Joey", "...")
speak("Tess", "Let's leave.")
speak("Joey", "Connie...")
