speak("Nadine", "Hullo, ummm uhhh...")
speak("Nadine", "Lia! Hi Lia.")
speak("Lia", "Hi Nadine. This is - ")
speak("Nadine", "Wait! Hang on, let me guess...")
speak("Nadine", "...")
speak("Nadine", "Nothing, sorry. I need to hit the cards, it looks like.")
speak("Lia", "This is Tess. She's new here.")
speak("Nadine", "Oh, alright. Bit of a quiet one, are you?")
speak("Lia", "N9 has affected her speech pathways. Read what she's typing to you on the screen.")
speak("Tess", "Please remember me, Nadine.")
speak("Nadine", "Haha, I'll do my best, Tess. But sometimes that's just how it is.")
speak("Nadine", "I know! Hold still and I'll get my camera.")
speak("Tess", "That isn't necessary.")
speak("Nadine", "You've got such a cute face though! I wouldn't want to forget it.")
speak("Tess", "It was nice to meet you. Goodbye.")
speak("Lia", "U-uhm, isn't that a bit rude...?")
speak("Nadine", "Ahh, it's okay. Joining Ward #6 is tough.")
speak("Nadine", "I'll see you around, Tess! I'm sure we'll be good friends in the future.")
