speak("Dr. Gray", "Ah. Lia. Patient #2902 and... #2867 was it?")
speak("Tess", "It's Tess.")
speak("Dr. Gray", "Right. I was just checking to make sure you were adjusting well.")
speak("Dr. Gray", "Lia will show you around and introduce you to the other patients.")
speak("Dr. Gray", "Please don't forget you have a checkup with Dr. Cooper at 4:00. Have a good day.")
speak("Lia", "Are you alright, Tess? You look pale.")
speak("Tess", "No.")
speak("Lia", "Do you want to rest a bit? Should I get Cal?")
speak("Tess", "I am fine. Let's meet the others.")
