speak("Owen", "Oh, it's you, Lia. I was wondering who interrupted my practice.")
speak("Lia", "S-sorry. There's someone I'd like you to meet.")
speak("Tess", "It's me, Owen. Tess.")
speak("Owen", "Who are you and how do you know my name?")
speak("Lia", "This is Tess. She's joining Ward #6 and she'll be my new roommate.")
speak("Owen", "It's been decided for sure?")
speak("Lia", "I think so.")
speak("Owen", "Then they've completely given up?")
speak("Lia", "I don't think Cecily is coming back, Owen.")
speak("Owen", "Bastards. Dying is bad enough. Disrespecting her memory by not telling us a thing... That's worse.")
speak("Owen", "It's like she never existed at all.")
speak("Owen", "Oh. Sorry there Tess. I got a little carried away. This doesn't concern you.")
speak("Tess", "It does.")
speak("Owen", "It doesn't.")
speak("Tess", "Cecily is the old occupant of 604. She vanished and left you an ambiguous note telling you not to worry.")
speak("Owen", "You... What?")
speak("Owen", "What do you know about Cecily? Where did you hear any of that?")
speak("Tess", "Because I was there.")
speak("Owen", "You were... Wait...")
speak("Tess", "You might not remember it but we've met before.")
speak("Owen", "Spare me the cheap acting. If you're here on Dr. Gray's orders, I don't have another word for you.")
speak("Owen", "I know the doctors love their mindgames but this is another level.")
speak("Tess", "Owen, please listen to me.")
speak("Owen", "I may have N9 but I am not a fool. Go away.")

speak("Lia", "Tess, what did you type to him? You uhm, you might've ticked him off.")
speak("Tess", "It's fine. Tell him to meet me tonight.")
speak("Lia", "You're a uhm, very forward person aren't you?")
speak("Tess", "Just tell him what I said, okay?")
speak("Lia", "O-okay.")
