if getSwitch('day3_04') then
    speak("Owen", "I may have N9 but I am not a fool. Go away.", 'd3_owen0')
    return
end

faceOther('d3_owen0', 'lia_bot')
speak("Owen", "Oh, it's you, Lia. I was wondering who interrupted my practice.", 'd3_owen0')
speak("Lia", "S-sorry. There's someone I'd like you to meet.", 'lia_bot')
faceOther('d3_owen0', 'hero')
speak("Tess", "It's me, Owen. Tess.")
speak("Owen", "Who are you and how do you know my name?", 'd3_owen0')
speak("Lia", "This is Tess. She's joining Ward #6 and she'll be my new roommate.", 'lia_bot')
faceOther('d3_owen0', 'lia_bot')
speak("Owen", "It's been decided for sure?", 'd3_owen0')
speak("Lia", "I think so.", 'lia_bot')
speak("Owen", "Then they've completely given up?", 'd3_owen0')
speak("Lia", "I don't think Cecily is coming back, Owen.", 'lia_bot')
speak("Owen", "Bastards. Dying is bad enough. Disrespecting her memory by not telling us a thing... That's worse.", 'd3_owen0')
speak("Owen", "It's like she never existed at all.", 'd3_owen0')
faceOther('d3_owen0', 'hero')
speak("Owen", "Oh. Sorry there Tess. I got a little carried away. This doesn't concern you.", 'd3_owen0')
speak("Tess", "It does.")
speak("Owen", "It doesn't.", 'd3_owen0')
speak("Tess", "Cecily used to be in 604. She vanished and left you an ambiguous note saying not to worry.")
speak("Owen", "You... What?", 'd3_owen0')
wait(.2)
face('d3_owen0', 'EAST')
wait(.4)
faceOther('d3_owen0', 'hero')
wait(.1)
speak("Owen", "What do you know about Cecily? Where did you hear any of that?", 'd3_owen0')
speak("Tess", "Because I was there.")
speak("Owen", "You were... Wait...", 'd3_owen0')
speak("Tess", "You might not remember it but we've met before.")
speak("Owen", "...", 'd3_owen0')
wait(1)
speak("Owen", "Hm...", 'd3_owen0')
wait(1)
speak("Owen", "Spare me the cheap acting. If you're here on Gray's orders, I don't have another word for you.", 'd3_owen0')
speak("Owen", "I know the doctors love their mindgames but this is another level.", 'd3_owen0')
face('d3_owen0', 'NORTH')
speak("Tess", "Owen, please listen to me.")
speak("Owen", "I may have N9 but I am not a fool. Go away.", 'd3_owen0')

wait(.8)
teleport('HallA', 'd1_target2')
face('hero', 'WEST')
spawnFollower('lia_bot', 'd1_target3')
face('lia_bot', 'EAST')
wait(.5)


speak("Lia", "Tess, what did you type to him? You uhm, you might've ticked him off.", 'lia_bot')
speak("Tess", "It's fine. Tell him to meet me tonight.")
speak("Lia", "You're a uhm, very forward person aren't you?", 'lia_bot')
speak("Tess", "Just tell him what I said, okay?")
speak("Lia", "O-okay.", 'lia_bot')

setSwitch('day3_04_owen', true)
play('day3_intro')
