speak("Lia", "Oh. You're finally awake.")
speak("Tess", "Sorry. It was rough last night.")
speak("Lia", "I didn't even hear you come in. I'm Lia, by the way.")
speak("Tess", "Yes?")
speak("Lia", "Uhm, well, welcome to Ward #6. It looks like we'll be roommates, so, it's nice to meet you.")
speak("Lia", "Your name is Tess, right?")
speak("Tess", "Yes.")
speak("Lia", "I'm sorry I haven't cleaned out all the stuff that's still here. It's all from my old roommate, but you'll have some space soon.")
speak("Tess", "These are mine. Don't touch them.")
speak("Tess", "I'm worried about you. You should probably see Dr. Cooper.")
speak("Lia", "You mean... Cal? I'm not sure what you mean.")
speak("Lia", "Let me know when you're ready and I can give you a tour of Ward #6.")
speak("Lia", "Allsaints is a pediatric hospital, so there's a bunch of people our age here. And everyone is N9 positive.")
speak("Tess", "Don't do this to me Lia.")
speak("Lia", "I-I don't mind at all. I have a lot of friends here. I'm supposed to introduce you.")
speak("Tess", "Lia, we've met before. Can you not remember?")
speak("Lia", "How much do you know about Neural-9? It usually causes memory loss, so, if you're a little confused, it's okay.")
speak("Tess", "I am not confused.")
speak("Tess", "Please follow me.")
speak("Lia", "U-uhm, alright. Do you know where you're headed?")