spawnFollower('lia_bot', 'room_yours')
wait(.1)
face('lia_bot', 'NORTH')

speak("Dr. Gray", "Ah. Lia. Patient #2902 and... #2867 was it?", 'd3_gray0')
speak("Tess", "It's Tess.")
speak("Dr. Gray", "Right. I was just checking to make sure you were adjusting well.", 'd3_gray0')
speak("Dr. Gray", "Lia will show you around and introduce you to the other patients.", 'd3_gray0')
speak("Dr. Gray", "Please don't forget you have a checkup with Dr. Cooper at 4:00.", 'd3_gray0')
walk('d3_gray0', 10, 'EAST', false)
face('hero', 'EAST')
wait(.8)
speak("Lia", "Are you alright, Tess? You look pale.", 'lia_bot')
face('hero', 'SOUTH')
speak("Tess", "No.")
speak("Lia", "Do you want to rest a bit? Should I get Cal?", 'lia_bot')
speak("Tess", "I'm fine. Let's meet the others.")

setSwitch('day3_01_gray', true)
