speak("Owen", "That's not right at all! Damn it.")
speak("Owen", "Why do you not work, you stupid fingers?")
speak("Owen", "I can practice all day long and nothing will ever happen...")
speak("Owen", "...")
speak("Owen", "How do I get out of here? If I get out, who will I be?")
