playSFX("madness")
speak("Dr. Gray", "Oh.", 'd5_gray')
speak("Dr. Gray", "It's quite unexpected that you would still be here.", 'd5_gray')
fadeOutBGM(.8)
speak("Dr. Gray", "But you have been replaced. Thank you, but you are no longer required.", 'd5_gray')
wait(.8)
speak("Dr. Gray", "You are just a bug in the system.", 'd5_gray')
wait(.4)
cs_endgame()
await()