speak("Lia", "Tess? Where are you going?")
speak("Tess", "Don't worry about it.")
speak("Lia", "Y-you know there's a curfew right?")
speak("Tess", "Don't. Worry.")
speak("Lia", "Maybe I should come with you.")
speak("Tess", "I think Owen might've been right about you.")
speak("Tess", "Are you really just a patient here?")
speak("Lia", "...")
speak("Tess", "Goodnight, Lia.")
