speak("Dr. Cooper", "Tess.")
speak("Dr. Cooper", "Sheesh, don't look so shocked. It's just me. Or were you expecting someone else?")
speak("Tess", "You caught me by surprise.")
speak("Tess", "I didn't mean to intrude, I just got lost going to the bathroom.")
speak("Dr. Cooper", "Nice try, Tess, but I know you better than that.")
speak("Tess", "What're you doing here anyway?")
speak("Dr. Cooper", "This is my lab. I'm allowed to be here past midnight if I want.")
speak("Dr. Cooper", "You aren't though. I can't have you running around here pulling power switches.")
speak("Dr. Cooper", "I'm getting really really close, and that'd really set my progress back! Ahahaha.")
speak("Tess", "I'll go back to my room.")
speak("Dr. Cooper", "Think you'll get off the hook so quickly?")
speak("Dr. Cooper", "Follow me.")
speak("Dr. Cooper", "Oh come on. You know me. It's nothing sinister. Here, I'll explain on the way.")
speak("Dr. Cooper", "Don't tell Dr. Gray, but I'm so extremely frustratingly close to getting to the root of Neural-9.")
speak("Tess", "A cure?")
speak("Dr. Cooper", "That's exactly it! Er, I mean, I'm not working on a cure, but a solution to the sort of thinking where we'd require a cure.")
speak("Dr. Cooper", "We've been approaching the problem all wrong. Or at least I have. Who knows what Dr. Gray's been up to.")
speak("Dr. Cooper", "But the point is, we've been taking an epidemiological approach, or sometimes a neurological one, but...")
speak("Dr. Cooper", "You can't cure Neural-9 because it's not a disease. It's more like... a property.")
speak("Dr. Cooper", "It's an innate quality of being. Like being a natural artist, or a quick thinker, or a piano prodigy. You're born with it.")
speak("Dr. Cooper", "Make sense?")
speak("Tess", "None.")
speak("Dr. Cooper", "This is a good a place as any.")
speak("Dr. Cooper", "Maybe it's just my fortune that you showed up here tonight Tess. Or did you know I'd be here in advance?")
speak("Tess", "I did not.")
speak("Dr. Cooper", "All the same, I'm glad it's you.")
speak("Dr. Cooper", "Hold still.")
speak("Tess", "Alright.")
speak("Dr. Cooper", "Keep your gaze steady.")
speak("Tess", "Alright.")
speak("Dr. Cooper", "Ready?")
speak("Dr. Cooper", "Now... Look directly into my eyes.")
speak("Dr. Cooper", "Don't blink. Don't waver. I want to truly see!")