speak("Lia", "Thanks for showing me around today.")
speak("Tess", "No problem. Thanks for helping us all look for Connie.")
speak("Lia", "It was fun! Seeing Joey so thrilled to have her back...")
speak("Tess", "You'll fit right in here.")
speak("Lia", "I've... never really fit in anywhere.")
speak("Lia", "Since I found out I had caught N9, no one wanted anything to do with me. Even if I covered my eyes.")
speak("Lia", "I sort of wondered, you know, what if the acid really had blinded me? Could I go back to normal?")
speak("Tess", "Even if we can't spread N9, we're still cursed with it.")
speak("Lia", "It was just a dumb dream.")
speak("Lia", "But everyone here seems so alive even if you've all got it way worse than me. It's almost nice here.")
speak("Lia", "Were you ever bullied before you came here?")
speak("Tess", "I can't remember that far back.")
speak("Lia", "It gets t-that bad? When do your memories start?")
speak("Tess", "I think I've been here a long time. No one else remembers when I showed up.")
speak("Lia", "Oh...")
speak("Lia", "Maybe that explains why you seem to get along so easily with everyone.")
speak("Lia", "I wonder if someone like me could be like you.")
speak("Tess", "Actually, if I could ask you a question.")
speak("Lia", "...?")
speak("Tess", "What year is it?")
speak("Lia", "You don't remember THAT? I...")
speak("Tess", "No. Tell me the answer.")
speak("Lia", "Uhm, I-I...")
speak("Tess", "You too?")
speak("Lia", "Maybe...")
speak("Tess", "Hold on to your memories of the outside world. Even if they're bad ones.")
speak("Tess", "You might be the only patient in Ward #6 who still has them.")
speak("Lia", "I-I will.")
speak("Tess", "I promised I'd meet up with Owen tonight.")
speak("Tess", "Don't wait up for me, and if some nurse tries to check up on us, say I'm in the bathroom or somewhere.")
speak("Tess", "Goodnight.")
