rotateTo('n2_joey')
speak("Joey", "Connie...", 'n2_joey')
speak("Tess", "Joey, what're you doing up?")
speak("Joey", "Looking for Connie...", 'n2_joey')
speak("Tess", "Go back to your room. It's late.")
speak("Joey", "Have you seen Connie?", 'n2_joey')
speak("Tess", "Connie isn't here.")
speak("Joey", "Tess... You'll help me find her?")
speak("Tess", "Joey, you need to go back to your room, or I'm finding a nurse.", 'n2_joey')
face('n2_joey', 'NORTH')
speak("Joey", "I think I see her! Let me go!", 'n2_joey')

walk('n2_joey', 3, 'SOUTH')
rotateTo('n2_joey')
walk('n2_joey', 6, 'SOUTH')
setSwitch('night2_02_joey', true)
