fadeOutBGM(1.8)
fade('fade_long')
setSwitch('n2_clear', true)
wait(.6)
intertitle("WHITE SLEET, VACANT SKY, SOUTHERN WIND\nMORNING AURA, OCEANS HUE,\nABLUTION, ABSOLUTION\n\nTABULA RASA\n\n\nDAY_3")
setSwitch('night', false)
teleport('RoomYours', 'start')