speak("Joey", "Connie...")
speak("Tess", "Joey, what're you doing up?")
speak("Joey", "Looking for Connie...")
speak("Tess", "Go back to your room. It's late.")
speak("Joey", "Have you seen Connie?")
speak("Tess", "Connie isn't here.")
speak("Joey", "Tess... You'll help me find her?")
speak("Tess", "Joey, you need to go back to your room, or I'm finding a nurse.")
speak("Joey", "I think I see her! Come on!")
