rotateTo('n2_target_rotate')

speak("Owen", "...is the only part I don't understand.", 'n2_owen')
speak("Dr. Cooper", "None of that happened! You're out in left field. N9 is making you nuts!", 'n2_cal')
speak("Owen", "How can you say that for sure? Isn't your memory affected now too?", 'n2_owen')
speak("Dr. Cooper", "Haha.", 'n2_cal')
speak("Owen", "Is that what you're trying to do? Just forget everything?", 'n2_owen')
speak("Dr. Cooper", "Wait...", 'n2_cal')
faceOther('n2_cal', 'hero')
faceOther('n2_owen', 'hero')
speak("Dr. Cooper", "Who goes there!?", 'n2_cal')
speak("Dr. Cooper", "C-Cecily?", 'n2_cal')
speak("Tess", "Are you alright Dr. Cooper?")
walk('n2_cal', 1, 'SOUTH')
faceOther('n2_cal', 'hero')
speak("Dr. Cooper", "Stay back! I swear it wasn't me. Wasn't even my idea!", 'n2_cal')
speak("Tess", "What are you talking about?")
speak("Dr. Cooper", "Say something! Anything!", 'n2_cal')
speak("Tess", "Dr. Cooper, please just read the screen. You know I can't speak.")
walk('n2_cal', 1, 'NORTH')
faceOther('n2_cal', 'hero')
speak("Dr. Cooper", "You're lying! You're lying! You - ")
speak("Owen", "Tess! He's not right! Get out of here!", 'n2_owen')

rotateTo('n2_target1')
pathTo('n2_target1')
rotateTo('n2_target2')
walk('hero', 8, 'NORTH', false)
fade('black')
teleport('Connector', 'in')
setSwitch('night2_06_cal', true)
