rotateTo('n3_cal')
setDepthMult(.75)
speak("Dr. Cooper", "Cecily!", 'n3_cal')
speak("Tess", "I am not Cecily.")
speak("Dr. Cooper", "Hahaha! Maybe you're not. You don't look like her.", 'n3_cal')
speak("Dr. Cooper", "But then who are you? That's what I thought I had figured out!", 'n3_cal')
speak("Tess", "I'm Tess.")
speak("Dr. Cooper", "That's not an identity! That's an experiment number!", 'n3_cal')
walk('n3_cal', 3, 'EAST')
rotateTo('n3_cal')
speak("Dr. Cooper", "Use that brain of yours! I know, deep down, that you can remember who you really are.", 'n3_cal')
speak("Tess", "I can't remember.")
speak("Dr. Cooper", "You can. I know you can. You're the culmination of everything I've worked towards.", 'n3_cal')
walk('n3_cal', 1, 'WEST')
speak("Dr. Cooper", "Who are you? Who are you? I have proved myself worthy. Please tell me!", 'n3_cal')
speak("Tess", "You're irrational, Dr. Cooper.")
speak("Dr. Cooper", "Why do you insist on typing? Drop the charade. Speak. Speak!", 'n3_cal')
walk('n3_cal', 1, 'WEST', false)
rotateTo('n3_cal')
speak("Dr. Cooper", "Why do you just stand there? What do I have to do to prove myself to you?", 'n3_cal')
speak("Tess", "Who do you think that I am?")
speak("Dr. Cooper", "I... You...", 'n3_cal')
walk('n3_cal', 1, 'SOUTH')
rotateTo('n3_cal')
wait(1)
faceOther('n3_cal', 'hero')
wait(.5)
setDepthMult(.5)
speak("Dr. Cooper", "You are someone powerful and all-knowing. You knew my name. You knew the questions.", 'n3_cal')
speak("Dr. Cooper", "You were the first to find the rabbit. It was...", 'n3_cal')
speak("Dr. Cooper", "You walk through life like you know every step of the way. You can know the future!", 'n3_cal')
speak("Tess", "Because I've experienced it before.")
speak("Dr. Cooper", "Hahaha! Haha! That's it! You admit it! You have experienced events before they actually occur!", 'n3_cal')
speak("Tess", "Becase they repeat.")
speak("Dr. Cooper", "To one as all-knowing as your royalness, maybe. But to a mortal like me...", 'n3_cal')
walk('n3_cal', 1, 'NORTH')
rotateTo('n3_cal')
speak("Dr. Cooper", "From the moment you walked into my lab today, I knew it was you. You called me by my name.", 'n3_cal')
faceOther('n3_cal', 'hero')
speak("Dr. Cooper", "I had forgotten I even had a name! But you knew. You even predicted all my questions!", 'n3_cal')
setDepthMult(.3)
speak("Dr. Cooper", "You, who knows everything about me, and the path before me...", 'n3_cal')
walk('n3_cal', 1, 'WEST')
rotateTo('n3_cal')
wait(1)
faceOther('n3_cal', 'hero')
caldeath(0)
speak("Dr. Cooper", "SPEAK! I COMMAND YOU TO SPEAK!", 'n3_cal')
speak("Dr. Cooper", "I demand my reward for awakening you! Tell me the great purpose for which I was placed into this world!", 'n3_cal')
speak("Tess", "Dr. Cooper, I can't tell the future.")
speak("Tess", "It's more likely that you have forgotten the past.")
speak("Dr. Cooper", "IMPOSSIBLE!", 'n3_cal')
walk('n3_cal', 2, 'WEST')
rotateTo('n3_cal')
speak("Dr. Cooper", "You blasphemer. You unholy, you abomination, you, you, you, you - ", 'n3_cal')
speak("Tess", "It was three nights ago that you exposed yourself to Neural-9, through my eyes.")
speak("Tess", "You are likely suffering from terminal N9.")
walk('n3_cal', 1, 'EAST', false)
speak("Dr. Cooper", "LIAR LIAR LIAR LIAR LIAR - ", 'n3_cal')
caldeath(1)
setSprite('n3_cal', 'cal_eyeless')
speak("Dr. Cooper", "I hearby rid myself of my vision. Now if you want to tell me lies, you must speak them.", 'n3_cal')
speak("Dr. Cooper", "Well then, #2876? Cecily? Whoever you are? Have I proved myself?", 'n3_cal')
speak("Tess", "Dr. Cooper, can you read me?")
face('n3_cal', 'NORTH')
speak("Dr. Cooper", "Well then? Well? Have I?", 'n3_cal')
wait(1)
setDepthMult(2)
face('n3_cal', 'EAST')
speak("Dr. Cooper", "I can't hear your voice.", 'n3_cal')
wait(.5)
face('n3_cal', 'WEST')
speak("Dr. Cooper", "Tell me... Just tell me...", 'n3_cal')
faceOther('n3_cal', 'hero')
speak("Dr. Cooper", "Tell me it meant anything.", 'n3_cal')

fadeOutBGM(1.5)
fade('fade_long')
intertitle("AUTOENUCLEATION (n.)\n\nTHE DESTRUCTION\nOF ONES OWN EYES\nBY ONES OWN HAND\n\nDAY_4")
setSwitch('night', false)
setSwitch('n3_clear', true)
teleport('Office1', 'target')
