speak("Owen", "...is the only part I don't understand.")
speak("Dr. Cooper", "You're out in left field. You're paranoid. You can blame N9.")
speak("Owen", "How can you say that for sure? Isn't your memory affected now too?")
speak("Dr. Cooper", "Haha.")
speak("Owen", "Is that what you're trying to do? Just forget everything?")
speak("Dr. Cooper", "Wait...")
speak("Dr. Cooper", "Who goes there!?")
speak("Dr. Cooper", "C-Cecily?")
speak("Tess", "Are you alright Dr. Cooper?")
speak("Dr. Cooper", "Stay back! I swear it wasn't me. Wasn't even my idea!")
speak("Tess", "What are you talking about?")
speak("Dr. Cooper", "Say something! Anything!")
speak("Tess", "Dr. Cooper, please just read the screen. You know I can't speak.")
speak("Dr. Cooper", "You're lying! You're lying! You - ")
speak("Owen", "Tess! Get out of here! He's not right!")