speak("Dr. Cooper", "Cecily!")
speak("Tess", "I am not Cecily.")
speak("Dr. Cooper", "Hahaha! Maybe you're not. You don't look like her.")
speak("Dr. Cooper", "But then who are you? That's what I thought I had figured out!")
speak("Tess", "I'm Tess.")
speak("Dr. Cooper", "That's not an identity! That's an experiment number!")
speak("Dr. Cooper", "Remember. I know, deep down, that you remember who you really are.")
speak("Tess", "I can't.")
speak("Dr. Cooper", "You can. I know you can. You're the culmination of everything I've worked towards.")
speak("Dr. Cooper", "Who are you? Who are you? I have proved myself worthy. Please tell me!")
speak("Tess", "You're irrational, Dr. Cooper.")
speak("Dr. Cooper", "Why do you insist on typing? Drop the charade. Speak. Speak!")
speak("Dr. Cooper", "Why do you just stand there? What do I have to do to prove myself to you?")
speak("Tess", "Who do you think that I am?")
speak("Dr. Cooper", "I... You...")
speak("Dr. Cooper", "You are someone powerful and all-knowing. You knew my name. You knew the questions.")
speak("Dr. Cooper", "You were the first to find the rabbit. It was...")
speak("Dr. Cooper", "You walk through life like you know every step of the way. You can know the future!")
speak("Tess", "Because I've experience it before.")
speak("Dr. Cooper", "Hahaha! Haha! That's it! You admit it! You have experienced events before they actually occur!")
speak("Tess", "Becase they repeat.")
speak("Dr. Cooper", "To one as all-knowing as your royalness, maybe. But to a mortal like me...")
speak("Dr. Cooper", "From the moment you walked into my lab today, I knew it was you. You called me by my name.")
speak("Dr. Cooper", "I had forgotten I even had a name! But you knew. You even knew all my questions before I asked them!")
speak("Dr. Cooper", "You, who knows everything about me, and the path before me...")
speak("Dr. Cooper", "SPEAK! I COMMAND YOU TO SPEAK!")
speak("Dr. Cooper", "I demand my reward for awakening you! Tell me the great purpose for which I was placed into this world!")
speak("Tess", "Dr. Cooper, I can't tell the future.")
speak("Tess", "It's more likely that you have forgotten the past.")
speak("Dr. Cooper", "IMPOSSIBLE!")
speak("Dr. Cooper", "You blasphemer. You unholy, you abomination, you, you, you, you - ")
speak("Tess", "It was three nights ago that you exposed yourself to Neural-9, through my eyes.")
speak("Tess", "You are likely suffering from terminal N9.")
speak("Dr. Cooper", "LIAR LIAR LIAR LIAR LIAR - ")
caldeath(0)
speak("Dr. Cooper", "I hearby rid myself of my eyes. Now if you want to tell me lies, you must speak them.")
speak("Dr. Cooper", "Well then, #2876? Cecily? Whoever you are? Have I proved myself?")
speak("Tess", "Dr. Cooper, can you read me?")
speak("Dr. Cooper", "Well then? Well? Have I?")
speak("Dr. Cooper", "I can't hear your voice.")
speak("Dr. Cooper", "Tell me... Just tell me...")
speak("Dr. Cooper", "Tell me it meant anything.")
caldeath(1)
