speak("Owen", "Oh. Tess. You're early.")
speak("Tess", "It's midnight. You lost track of time.")
speak("Owen", "So I did.")
speak("Owen", "But you could at least knock next time...")
speak("Tess", "What did you want to talk about? You had a lead on Cecily?")
speak("Owen", "I don't want to get ahead of myself. Let's start with something normal first.")
speak("Owen", "Did Cooper change anything up today?")
speak("Tess", "Same questions as always.")
speak("Owen", "Why is he only interested in your brainwaves? It doesn't make any sense.")
speak("Tess", "You always say it doesn't make sense.")
speak("Owen", "Because it never has. Sure, Neural-9 is a neurodegenerative disease, but so are Parkinson's, Alzheimer's, and so on.")
speak("Owen", "The dangerous part is the infection vector. Eye contact. How does that make any sense?")
speak("Owen", "Shouldn't they be studying that, and not what exactly is going on in our brains? Who cares about that. Just stop the spread.")
speak("Owen", "I think Cooper and Gray and everyone else is lying about the eye thing.")
speak("Tess", "Why?")
speak("Owen", "It makes no phsyical sense -- that's the biggest reason. But partially because we have no ways to verify anything with the outside world.")
speak("Owen", "That's a theory Cecily and I had. What symptom did Joey, Nadine, you, me, and her all had in common?")
speak("Tess", "Couldn't remember the outside.")
speak("Owen", "So Gray and the rest could lie to us, and as long as no one brings information from outside, we have no choice but to believe them.")
speak("Owen", "N9 might not even be contagious. That could be a ruse to deny us any visitors. To deny us information.")
speak("Tess", "But what would the point of that be?")
speak("Tess", "Besides, Lia remembers the outside. We can just ask her.")
speak("Owen", "She does?")
speak("Owen", "...")
speak("Owen", "You don't find it strange that just when Cecily and I came up with this theory, she vanishes?")
speak("Owen", "And some new girl shows up in her place, with information specifically to disprove it?")
speak("Tess", "I think you're paranoid.")
speak("Owen", "Someone needs to be cautious around here. Since Cecily disappeared I feel like I have to be.")
speak("Tess", "I'd say you were nuts, but... we really can't figure out what happened to her.")
speak("Owen", "We're old enough where if she died of N9, Gray would tell us. She doesn't care about our feelings.")
speak("Owen", "Patient confidentiality is one thing, but what she left behind reads like a suicide note.")
speak("Tess", "Not really.")
speak("Owen", "Okay, maybe not the note she left for you. But she was my best friend. She sounded like...")
speak("Owen", "She knew something bad was going to happen and there was no stopping it.")
speak("Owen", "I don't care about the rest of the doctors' lies, but I am going to find Cecily. That's a line too far.")
speak("Tess", "I'm with you.")
speak("Owen", "The 'lead' I found isn't really a lead. But I found this.")
speak("Tess", "A key?")
speak("Owen", "It opens the service stairwell from the common room.")
speak("Tess", "What do you want me to do with it? Sneak out?")
speak("Owen", "There's no way we could get past building security but we could probably reach another floor, a non-N9 one.")
speak("Owen", "Anything to confirm we're not just goldfishes in a bowl for these people.")
speak("Tess", "Why me specifically?")
speak("Owen", "If you get caught, Cooper will pull strings and get you out of it. You're his favorite. You'll be fine.")
speak("Owen", "And... it just sort of made sense. I think Cecily left things in your hands.")
speak("Tess", "I won't let you down.")
speak("Owen", "You shouldn't care about me -- I don't matter. Do it for her.")