speak("Tess", "Excuse me Dr. Gray.")
speak("Dr. Gray", "Yes?", 'd1_gray2')
speak("Tess", "Do you know where Dr. Cooper is?")
speak("Dr. Gray", "I can relay a message.", 'd1_gray2')
speak("Tess", "The ward pet got free. We're looking for her and thought he could help.")
speak("Dr. Gray", "Dr. Cooper isn't paid to help you with things like that.", 'd1_gray2')
speak("Dr. Gray", "He may have low personal standards, but he's a skilled professional at the top of our field.", 'd1_gray2')
speak("Dr. Gray", "And I won't have him interrupted.", 'd1_gray2')
speak("Tess", "If there's a rabbit found in the rest of the hospital, could you let us know then?")
speak("Dr. Gray", "If I'm in the area.", 'd1_gray2')
speak("Dr. Gray", "Frankly a pet in a N9 ward is a terrible idea, around impressionable children...", 'd1_gray2')
speak("Dr. Gray", "...can thank Dr. Cooper's whimsy for that...", 'd1_gray2')
speak("Dr. Gray", "...course it was never going to end well...", 'd1_gray2')

walk('d1_gray2', 7, 'EAST')
setSwitch('day1_12_search_gray', true)
