if getSwitch('day1_11_search_owen') then
    speak("Owen", "Meet me tonight at the usual spot and we can talk when there are less ears around.", 'd1_owen2')
    return
end

faceOther('lia_bot', 'd1_owen2')
speak("Owen", "I don't suppose either of you have seen the rabbit yet.", 'd1_owen2')
speak("Tess", "No.")
speak("Owen", "Figures. It must've gotten downstairs.", 'd1_owen2')
speak("Owen", "Hopefully no one kills it because it's been exposed to N9.", 'd1_owen2')
faceOther('d1_owen2', 'lia_bot')
faceTo('lia_bot')
speak("Lia", "Animals can carry it?", 'lia_bot')
speak("Owen", "No idea. It's not a well-understood disease.", 'd1_owen2')
speak("Owen", "...which is surprising given how devastating it could be if an outbreak became a full-fledged epidemic.", 'd1_owen2')
speak("Owen", "If someone told me my pet might be contaminated with THAT... Well, I wouldn't take my chances.", 'd1_owen2')
speak("Lia", "That's horrible.", 'lia_bot')
speak("Owen", "You haven't shown symptoms yet. The older you get, the worse it becomes.", 'd1_owen2')
speak("Owen", "Have you seen what happens to infected adults?", 'd1_owen2')
speak("Lia", "No...", 'lia_bot')
speak("Owen", "You grew up really sheltered, didn't you?", 'd1_owen2')
speak("Owen", "The point is, there's a reason we're all locked up in here. We're contagious.", 'd1_owen2')
faceTo('d1_owen2')
faceOther('d1_owen2', 'hero')
speak("Tess", "You can ease up a bit. She's been here less than a day.")
speak("Owen", "Oh, right, Tess. I need to talk to you. I might have an idea about Cecily. But...", 'd1_owen2')
faceOther('d1_owen2', 'lia_bot')
wait(1.0)
faceOther('d1_owen2', 'hero')
speak("Owen", "Never mind. Meet me tonight at my room and we can talk when there are less ears around.", 'd1_owen2')

setSwitch('day1_11_search_owen', true)
