speak("Lia", "Oh. You're back. Hi Tess.", 'd2_lia4')
speak("Tess", "Hello.")
speak("Lia", "I wish I could've been more help looking for Connie...", 'd2_lia4')
speak("Tess", "You did fine.")
speak("Lia", "Ward #6 feels so different from yesterday. No one really wants to see me.", 'd2_lia4')
speak("Tess", "Everyone is processing, is all. We've had Connie for as long as I can remember.")
speak("Tess", "By the way, you did only show up here yesterday, correct?")
speak("Lia", "T-that's right.", 'd2_lia4')
speak("Tess", "Thank you. Sorry, sometimes with N9, it pays to double check.")
wait(.8)
speak("Lia", "Are you going to be sneaking out again tonight?", 'd2_lia4')
speak("Tess", "I'm not sure.")
speak("Lia", "Oh.", 'd2_lia4')
speak("Tess", "But if you could cover for me again I'd be grateful.")
speak("Lia", "I will. I'll do whatever I can.", 'd2_lia4')
speak("Tess", "Goodnight.")

fade('black')
fadeOutBGM(1)
wait(1)
setSwitch('d2_clear', true)
setSwitch('spawn_lia', false)
intertitle("FRAILTY BEGETS FILTH\n\nAS THE BODY IS SLOUGHED OFF\n\nSO THE MIND IS FREED\n\n\n\nNIGHT_2")
setSwitch('night', true)

teleport('RoomYours', 'start')

