rotateTo('chair')
wait(0.5)
speak('ARIEL', "Whenever I have enough info, I can come here to Recurse and attempt to record a dream that explains it all.")
speak('ARIEL', "...Of course, it's not likely to work if I'm missing facts.")
setSwitch("finale_info", true)
