speak('ARIEL', "You can reveal yourself.")
speak('ARIEL', "You don't need to hide in the shadows of my mind.")
speak('ARIEL', "Because this is not my mind. This is your mind, Dr. Kowalski.")
enterNVL()
enter('CHRIS', 'c')
speak('CHRIS', "I had hoped you wouldn't notice me.")
speak('ARIEL', "You've improved. You used to be hopeless at lucid dreaming.")
speak('CHRIS', "You read my dreamlog then. Yes, I've been practicing.")
speak('CHRIS', "I heard your theory, by the way. You're almost entirely correct.")
speak('CHRIS', "But it was me, not Braulio, that removed all references to oneirophrenia from your memory.")
speak('ARIEL', "Why?")
speak('CHRIS', "For the same reason you thought Braulio did. I wanted you to live on, peacefully, in the body of someone who hasn't suffered from Bluepill exposure since they were a child.")
speak('CHRIS', "If you realized that it was possible to create a false memory, you'd learn the truth.")
speak('CHRIS', "I see now that I should've simply erased myself from your memory entirely. Maybe I had too much of an ego to see it.")
speak('ARIEL', "Have you asked yourself why you felt the need to cover your tracks?")
speak('CHRIS', "For your sake. Even if you needed to be ignorant, I wanted you to be happy. My research directly led to your death. I had nothing to live for, and I needed to atone.")
fadeOutBGM(1)
playBGM('finale')
speak('ARIEL', "I think you've miscalculated.")
speak('ARIEL', "You've put your atonement first, and me second.")
speak('ARIEL', "Because you do have something to live for, Dr. Kowalski. Only you can put an end to Sumi Chey and her designs on Lucir.")
speak('ARIEL', "I'm clearly still unwell. No matter what body I'm in, I'm afraid if it has my ego, it will always deteriorate and die. I'm back in these hallways of death, after all.")
speak('ARIEL', "But Dr. Kowalski, I've collected all the evidence for you in my final dream. You have the knowledge, and you have a body.")
expr('CHRIS', 'pain')
speak('CHRIS', "I don't. The amount of Bluepill I gave myself nearly killed me. I've been erased.")
expr('CHRIS', nil)
speak('ARIEL', "And I'm restoring you. Right now, your body is hooked up to Recurser, replaying all those memories you left behind in your journal.")
finaleCorridor()
speak('ARIEL', "All the beauty, all those surreal forests, and all the nightmares too. Everything that makes you the person you are. You will be that person again.")
speak('ARIEL', "I want you to use my death to end Recurser. You could be a researcher at any university in the world. Find a way to help Noemi, so she doesn't meet the same end as me.")
speak('CHRIS', "But what about you?")
speak('ARIEL', "Chris, for half my life I was used, without my knowledge or consent, by people who thought they were serving a higher cause.")
speak('ARIEL', "You've done the same thing, even if your cause was a fair bit more noble than theirs.")
speak('ARIEL', "But I reject your offer. I've already died, and if you're able to use that fact to stop Sumi and save Noemi...")
speak('ARIEL', "...then I have no regrets. I've already found my freedom in my dreams.")
speak('ARIEL', "Goodbye, Chris, and good luck. The rest of this life is yours to lead.")
fadeOutBGM(3)
endGame()
