if not getSwitch('pt1_05b') then
	enterNVL()
	speak('ARIEL', "Noemi? Noemi wake up. Sumi wants to meet you.")
	speak('ARIEL', "Noemi, come on.")
	enter('SUMI', 'b', 'surprise')
	speak('SUMI', "She's asleep standing up?")
	speak('ARIEL', "You can never really tell with Noemi.")
	speak('ARIEL', "Noemi!")
	expr('SUMI', nil)
	speak('SUMI', "This looks like a bad time.")
	speak('ARIEL', "It's as good as any. She's always like this.")
	enter('NOEMI', 'd', 'happy')
	speak('NOEMI', "Like what?")
	speak('ARIEL', "Oh, you're awake, sort of. Noemi, Sumi wanted to meet you.")
	speak('SUMI', "Braulio mentioned you. It's my pleasure.")
	speak('ARIEL', "Noemi, Sumi's trying to shake hands.")
	expr('NOEMI', nil)
	speak('NOEMI', "Ah. Nice to meet you, Sumi.")
	speak('SUMI', "I'm sorry, I didn't realize you were blind.")
	speak('NOEMI', "It's not that I'm...")
	speak('NOEMI', "Ariel can explain.")
	speak('ARIEL', "She's asleep at the moment. Vision doesn't quite work the same in dreams as it does when you're awake.")
	expr('SUMI', 'intense')
	speak('SUMI', "So she's... sleepwalking?")
	speak('NOEMI', "Humans waste a third of their life sleeping. But with just the right amount of Bluepill, at the same time I'm talking to you here, I can be writing code in the dream world.")
	speak('SUMI', "How unconventional.")
	speak('NOEMI', "I've found I program more fluently in a trance than when I'm truly awake. And I can work through the night while everyone else dreams unproductive dreams.")
	speak('ARIEL', "She hasn't woken up in a month, probably.")
	expr('SUMI', nil)
	speak('SUMI', "You don't find that... inconvenient?")
	speak('NOEMI', "It's reality that's inconvenient. I'm still experimenting with the sedative dose, and Chris says I've probably developed too much of a tolerance for Bluepill at this point, but...")
	expr('NOEMI', 'happy')
	speak('NOEMI', "I'm much happier like this.")
	expr('SUMI', nil)
	speak('SUMI', "If you say so.")
	speak('NOEMI', "Would you like to meet the rats? They work here too.")
	speak('ARIEL', "Noemi, don't show her the lab rats.")
	expr('NOEMI', 'happy')
	speak('NOEMI', "This is Ratilda. Rattheus is asleep now, but Ratrick should be around here somewhere...")
	speak('ARIEL', "See you later, Noemi.")
	exitNVL()
	
	teleport('F2', 'noemi', 'WEST')
	wait(0.8)
	enterNVL()
	enter('SUMI', 'c')
	wait(0.2)
	speak('ARIEL', "Sorry, Noemi is a little odd, but she's an old friend of mine. Plus she programmed Gazer basically from scratch.")
	speak('ARIEL', "Computational neuroscience is her specialty. All the technology that lets us record and play back brain signals -- that's all her work.")
	speak('SUMI', "Genius and insanity go hand in hand, after all.")
	speak('ARIEL', "She's not insane, she - ")
	speak('SUMI', "Ahaha, I'm only joking. She seems like a nice girl. Maybe later I'll have time to meet the rats.")
	exitNVL()
else
	speak('ARIEL', "Looks like Noemi's attention is on her dream again.")
end

setSwitch('pt1_05b', true)
play('pt1_05_tourcheck')
