teleport('Meeting', 'target', 'NORTH')
wait(.8)

enterNVL()
enter('BRAULIO', 'b')
enter('NOEMI', 'e')
enter('CHRIS', 'd')
speak('CHRIS', "You said there was news?")
speak('BRAULIO', "Sumi's in! Her holding group would take 25% equity, but we'd be funded in full for the next five years! And with enough to hire more staff and buy material for the next Gazer prototype.")
speak('ARIEL', "No objections here. Nice work.")
expr('NOEMI', 'happy')
speak('NOEMI', "You did it, Braulio.")
expr('NOEMI', nil)
expr('BRAULIO', 'unsure')
speak('BRAULIO', "There were a few strings attached, but, I guess there always are.")
speak('CHRIS', "Like what?")
expr('BRAULIO', nil)
speak('BRAULIO', "Nothing too serious! She wants to hang around for a week or two to observe how we work. I guess that's common for VCs?")
expr('CHRIS', 'thinking')
speak('CHRIS', "I've never heard of it.")
expr('CHRIS', 'pain')
speak('CHRIS', "Isn't that woman supposed to manage a multinational holdings company? How's she going to do that if she's sitting in the back of my lab, drilling into the back of my neck with those falcon eyes of hers?")
expr('CHRIS', nil)
expr('BRAULIO', 'determined')
speak('BRAULIO', "I offered her one of the empty offices. She'll be working from there and then spending down time looking over our tech.")
speak('NOEMI', "Maybe I should share some of research into dream projection... She could go back home, but leave her dream self here with us.")
expr('BRAULIO', nil)
speak('BRAULIO', "...Is that a real thing?")
speak('ARIEL', "It absolutely is not. You need to learn when Noemi is pulling your leg.")
speak('BRAULIO', "Oh, and Sumi wants us to demo mirroring for her.")
speak('CHRIS', "Braulio, you know we can't do that. It takes a receptive subject, not to mention the risk of ____.")
speak('CHRIS', "We've never even tried it with anyone other than Ariel and Noemi.")
speak('ARIEL', "Noemi and I will demo. There's no need for Sumi to experience mirroring herself -- she just needs to see that it works.")
speak('CHRIS', "If you're sure about this. If we end up with ____, we certainly won't be getting any funding.")
speak('BRAULIO', "What're the alternatives here though? The rent's high, but we can't afford to move anywhere else because half of our tech is on loan from Aquila.")
speak('BRAULIO', "We could try raising funds by minting Lucir-coin, like I offered last time we - ")
speak('CHRIS', "Absolutely not.")
speak('ARIEL', "We are not making a cryptocurrency.")
speak('NOEMI', "I thought that was a joke...")
expr('BRAULIO', 'angry')
speak('BRAULIO', "I get it, I get it! But we're out of options here, and Sumi looks like our best bet to bring Gazer to market. So let's do this demo and let her hang around a bit.")
speak('CHRIS', "It's your call. I'll follow along.")
expr('BRAULIO', 'determined')
speak('BRAULIO', "Then Ariel, could you grab Sumi? Let's do this demo and prove we're worth her time.")
exitNVL()

play('pt1_08')
