
enterNVL()
speak('CHRIS', "Ariel. Ariel! Are you alright?")
speak('NOEMI', "Hmmm. These delta waves... There's a flowing rhythm in them.")
setWake(1)
wait(2)
speak('CHRIS', "Does that mean Ariel's still asleep?")
speak('NOEMI', "Hm hm. Maybe and maybe not.")
setWake(1)
wait(2)
speak('ARIEL', "I'm awake. Sorry.")
enter('CHRIS', 'b')
enter('NOEMI', 'd')
setWake(-1)
speak('CHRIS', "There's no need to apologize. Did something happen? Your heart was beating so fast that I was afraid I'd overdosed you.")
speak('ARIEL', "Nothing happened.")
speak('NOEMI', "Whatever you were dreaming, I couldn't record it. Gazer didn't pick it up... Too bad.")
speak('ARIEL', "It wasn't a lucid dream. You wouldn't have wanted to record it anyway.")
speak('CHRIS', "Maybe it's a problem with the new formula... I'll change the balance back for next time.")
speak('NOEMI', "Or a bug with Gazer. I'm not perfect.")
speak('ARIEL', "Just a bug...")
exitNVL()

wait(1.5)
rotateTo('braulio_pt1')
wait(1.3)

enterNVL()
enter('BRAULIO', 'e')
speak('BRAULIO', "Hey! Listen up guys because you won't believe this! She's actually here, in person!")
enter('CHRIS', 'a')
enter('NOEMI', 'b')
speak('CHRIS', "Our mystery investor?")
speak('BRAULIO', "Yes! I didn't even know until yesterday that her group was interested, but she's in the meeting room now, and - ")
speak('BRAULIO', "Wait, Ariel, are you okay? You're shaking.")
speak('ARIEL', "It's nothing.")
speak('BRAULIO', "Okay, good, I'm glad you're okay, because she's looking to meet all of us. Like, right now.")
exitNVL()

setSwitch('pt1_02', true)
