if getSwitch('pt1_10c') then
	speak('ARIEL', "She doesn't respond.")
	speak('ARIEL', "I think it's time I admit that there's something very wrong with Noemi, not just her rats.")
	return
end

enterNVL()
speak('ARIEL', "Noemi? It's Ariel. I'm coming in.")
enter('NOEMI', 'c')
speak('NOEMI', "Dream Ariel or regular?")
speak('ARIEL', "Regular, boring Ariel.")
speak('ARIEL', "What're you doing here with the rats?")
expr('NOEMI', 'happy')
speak('NOEMI', "I'm giving Ratricia an EEG.")
speak('ARIEL', "Checking her brain waves? I thought it was Ratilda that was having trouble.")
expr('NOEMI',  nil)
speak('NOEMI', "Neither of them are moving now.")
speak('ARIEL', "That's a shame. Must be a disease going around.")
speak('NOEMI', "But look at her brain activity. Check the EEG.")
speak('ARIEL', "It's... moving a mile minute. Basically every center firing at once. Like solving calculus and playing a sonata at the same time.")
speak('NOEMI', "She's dreaming.")
speak('ARIEL', "You're sure it's not just random noise?")
speak('NOEMI', "Hm hm. Maybe not. But it reminds me of those kids, back then.")
speak('ARIEL', "From Ward No.9?")
exit('NOEMI')
wipe()
wait(0.7)
enter('NOEMI', 'a')
wait(0.5)
speak('NOEMI', "Whenever I sleep normally, without Bluepill, I see them in my dreams. Every night for ten years.")
speak('NOEMI', "Alice, lying there, twitching for days, dead to the world... I see her face a lot.")
speak('NOEMI', "Or that red-headed kid, who wouldn't stop trying to escape, so they'd duct tape him to the bed at night.")
speak('NOEMI', "The worst are the ones whose names I never knew. The girl in the next room who didn't speak, and only air came out when she opened her mouth...")
speak('NOEMI', "Or the boy in 1B that sobbed and sobbed and one day he was just gone.")
speak('NOEMI', "And sometimes I see you, from those days. You're like you always were, sitting in a corner, calm, like your spirit was somewhere else entirely.")
exit('NOEMI')
enter('NOEMI', 'c')
speak('NOEMI', "Do you still those nightmares, Ariel?")
wipe()
wait(.7)
speak('ARIEL', "No.")
speak('ARIEL', "All my dreams are lucid. I learned how to do it back then, so when I was alseep, I didn't have to see anything I didn't want to see. Being awake was enough of a nightmare.")
speak('ARIEL', "I'm pretty sure if I wasn't as disciplined about it, those nightmares would come for me as well.")
speak('NOEMI', "Once, I looked up that horrible place and that horrible study. No one mentions the abuse, of course.")
speak('NOEMI', "There was a funny coincidence, though. Do you know what the study was about?")
speak('ARIEL', "It was supposed to be a new treatment for childhood behavioral disorders, wasn't it?")
expr('NOEMI', 'happy')
speak('NOEMI', "They were trying to do it with Bluepill derivatives. That was back when Bluepill was supposed to cure everything from ADHD to depression.")
speak('NOEMI', "What a joke that would be... Both of us survive hell only to put the poor rats straight back into it.")
expr('NOEMI', 'shock')
speak('NOEMI', "Is that what's happening to Ratilda? Is she like Alice, trapped in a neverending dream?")
expr('NOEMI', nil)
speak('ARIEL', "Then let's be glad that we drugged rats and not children. Throw out every chemical Chris gave you this week, and let's forget about it.")
wipe()
wait(.7)
expr('NOEMI', 'shock')
speak('NOEMI', "Ow!")
speak('ARIEL', "Noemi!?")
speak('NOEMI', "She woke up and bit me! Where'd Ratricia go?")
speak('ARIEL', "She's going berserk... A seizure? But she's bouncing from one side of the cage to the other.")
expr('NOEMI', nil)
speak('NOEMI', "Sedate her. Please, Ariel.")
speak('ARIEL', "I'll try, but she's hard to catch. Stop flailing around, Ratricia.")
exitNVL()
rotateTo('look_target')
wait(1)
enterNVL()
enter('NOEMI', 'b')
speak('NOEMI', "Did you do it?")
speak('ARIEL', "She's slowing down. There. Back to sleep. Did you want to run another EEG?")
speak('NOEMI', "I'll try later.")
speak('ARIEL', "Are you going home, or are you just going to work all night again?")
expr('NOEMI', 'happy')
speak('NOEMI', "Work. Not-dream-Noemi needs to write down the facial recognition code that dream-Noemi thought up.")
expr('NOEMI', nil)
speak('ARIEL', "I'll leave you to it, then. Take a break some time though, alright?")

setSwitch('pt1_10c', true)
