enterNVL()
enter('CHRIS', 'c')
speak('CHRIS', "Ariel. I've been looking all over for you.")
speak('ARIEL', "You found something with the new formula?")
speak('CHRIS', "No. This is about _____.")
wipe()
wait(0.8)
speak('ARIEL', "...Sorry. Can you say that again?")
speak('CHRIS', "_____. Are you absolutely sure your report hasn't leaked outside Lucir? Is there any way Sumi Chey could know about it?")
speak('ARIEL', "I'm sorry, I really don't get what you're talking about.")
expr('CHRIS', 'pain')
speak('CHRIS', "What do you mean? Is it really that hard a question?")
expr('CHRIS', nil)
speak('CHRIS', "Well, I dug up some more information on long-term Bluepill use. There are other labs out there working on applications of Bluepill, and nothing as benign as Gazer.")
expr('CHRIS', 'thinking')
speak('CHRIS', "Actually...")
expr('CHRIS', nil)
speak('CHRIS', "Later tonight, once Braulio and Sumi are gone, come back to the tower.")
speak('CHRIS', "Meet me at the Floor 36 computer lab. I need to look up more info on the Chey Group, but I don't want those two sniffing around.")
speak('CHRIS', "Got it?")
speak('ARIEL', "I think so.")
speak('CHRIS', "Goodnight then.")
exit('CHRIS')
wipe()
wait(.8)

enter('CHRIS', 'e')
speak('CHRIS', "Oh and don't let Sumi anywhere near Gazer. Probably not Braulio either. I'll explain later.")
exitNVL()

fade('black')
setSwitch('pt1_10b', true)
fade('normal')
