wait(1.6)
enterNVL()
enter('SUMI', 'c')
wait(0.6)
enter('BRAULIO', 'a')
speak('BRAULIO', "Everyone, I'd like you to meet Sumi Chey. Ms. Chey, welcome to Lucir.")
speak('SUMI', "Just Sumi is fine.")
speak('SUMI', "You probably don't know me by name, but the Chey Group has a controlling stake in international businesses in the mining and energy sectors.")
speak('SUMI', "I'm looking to diversify, however, and venture capital seems to suit me. And I'm particularly fascinated by the work you're doing here at Lucir.")
speak('BRAULIO', "I have the pitch deck ready to go when you're comfortable.")
speak('SUMI', "Then let's see it.")
exit('SUMI')
speak('BRAULIO', "Alright! Here we go. Sorry, I've never actually presented this live before so bear with me if I make any mistakes. Usually Ariel talks to the press, or - ")
enter('CHRIS', 'a', 'pain')
speak('CHRIS', "Just start it, Braulio.")
exit('CHRIS')
expr('BRAULIO', 'determined')
speak('BRAULIO', "Right! Ahem.")
exit('BRAULIO')
enter('BRAULIO', 'c', 'angry')
speak('BRAULIO', "Almost ten percent of adults in the United States will be diagnosed with PTSD in their lifetime. Patients often suffer from nightmares or intrusive thoughts that feel beyond their ability to control.")
expr('BRAULIO', 'determined')
speak('BRAULIO', "Lucir is developing a dream experience system. By allowing patients to control their dreams or confront their nightmares, we can help provide relief.")
speak('BRAULIO', "Our product is Gazer, a machine that allows a patient to view specific dreams.")
speak('BRAULIO', "We've developed a working digital encoding of electrical signals, that, when played back, force the patient's brain into a predictable dreamlike experience.")
speak('BRAULIO', "Our revenue will come not only from selling Gazers, but from creating these dream replays and tailoring them to the needs of individual customers.")
speak('BRAULIO', "Of course, there's non-medical demand for this technology too -- imagine paying $9.99 and renting a dream of a tropical island, like a mini-vacation.")
expr('BRAULIO', nil)
speak('BRAULIO', "And um, this slide is the business analysis and our go-to-market plan. I sent you a copy, but I can go over this again if you - ")
enter('SUMI', 'e')
speak('SUMI', "That's quite alright.")
expr('SUMI', 'intense')
speak('SUMI', "Let's go back to Gazer. I distinctly remember you mentioning a certain drug.")
speak('BRAULIO', "Er, right. At the moment, the patient takes a small dose of cyanophazepam to put them into a suggestible state before sleeping. We're trying to find a way to work around that.")
expr('SUMI', 'intense')
speak('SUMI', "Cyano...")
enter('CHRIS', 'a')
speak('CHRIS', "Cyanophazepam. It's a psychedelic. If you've heard of it before, you've probably heard one of the street names. Cyan, Blue, Bluepill...")
exit('CHRIS')
expr('SUMI', nil)
speak('SUMI', "Right. Bluepill. That's the one. Yes, I've heard of it.")
expr('BRAULIO', 'determined')
speak('BRAULIO', "Like I said, we're trying to find an alternative.")
speak('SUMI', "Maybe we should skip ahead. You mentioned a tour?")
expr('BRAULIO', nil)
speak('BRAULIO', "Oh, right, right. The tour, and the demo. One second.")

speak('BRAULIO', "Ariel...")
speak('BRAULIO', "Do you mind showing Sumi around for me? I know I'm the founder and I should be doing it, but - ")
speak('ARIEL', "It's not a problem.")
speak('BRAULIO', "Thanks. I need to grab another coffee or something. You know that woman's worth, like, north of four billion dollars?")
speak('BRAULIO', "And I'm here sweating through my shirt and flubbing the pitch. You're always unflappable, though. I know I can trust you.")
speak('ARIEL', "Sure. Just show her the labs?")
speak('BRAULIO', "Yeah. Maybe, uh, avoid Noemi though.")
speak('NOEMI', "You needed me?")
speak('BRAULIO', "No! You're all good to get back to Gazer.")
speak('BRAULIO', "Sumi, I'd like you to meet Ariel. If you guys want to poke around the lab a bit, I'll get ready in the office with all the paperwork.")
speak('ARIEL', "Let's head outside.")
