enterNVL()
enter('SUMI', 'c')

if not getSwitch('pt1_09d') then
	expr('SUMI', 'surprise')
	--jolt('SUMI')
	speak('SUMI', "Miala tsiny fa tsy hitako teo ianao.")
	speak('ARIEL', "Sorry?")
	speak('SUMI', "'Sorry' what?")
	speak('ARIEL', "I didn't catch what you said.")
	expr('SUMI', 'intense')
	speak('SUMI', "I asked what you were up to and you looked at me like I had grown an extra head.")
	speak('ARIEL', "You must've slipped into some other language. It's not a big deal.")
	expr('SUMI', nil)
	speak('SUMI', "Ahaha. I must've coughed on my delivery. I only know English and the Latin the nuns beat into me in grammar school.")
	speak('ARIEL', "If you say so.")
	speak('ARIEL', "Everything is okay downstairs in the temporary office? You'll be able to work there for a few days?")
	speak('SUMI', "It's not perfect, but it'll work. Besides, I'm much more interested in learning how things work at Lucir.")
	speak('SUMI', "This is a bit random, but I love that crystal pendant you're wearing. Where did you get that?")
	speak('ARIEL', "Oh, this?")
	speak('ARIEL', "I...")
	speak('ARIEL', "Sorry, I don't remember. I think I've always been wearing this.")
	speak('SUMI', "It suits you well.")
	speak('ARIEL', "It's quartz. Cold, solid, regular. I like it.")
	expr('SUMI', 'intense')
	speak('SUMI', "But sharp edges though.")
	speak('ARIEL', "Fair enough.")
	expr('SUMI', nil)
	speak('SUMI', "Ahaha, I really do like you Ariel. You don't flinch. I'm looking forward to seeing you around for the next few weeks.")
	speak('ARIEL', "Well, I'm sure I speak for all of us when I say we appreciate your investment. Welcome to Lucir.")
	--jolt('SUMI')
	speak('SUMI', "Rehefa avy eo.")
	speak('ARIEL', "You too?")
else
	speak('SUMI', "I'm looking forward to seeing you around for the next few weeks.")
end

exitNVL()
setSwitch('pt1_09d', true)
