if not getSwitch('pt1_09c') then
	enterNVL()
	speak('ARIEL', "Noemi? It's Ariel. I'm coming in.")
	enter('NOEMI', 'c')
	speak('NOEMI', "Ariel! Can you check Ratilda?")
	speak('ARIEL', "She's, uh... Which one's Ratilda?")
	speak('NOEMI', "The one that isn't moving.")
	speak('ARIEL', "Oh. I see. She's still breathing... and she looks okay?")
	speak('NOEMI', "But she's so still...")
	speak('NOEMI', "Poor Ratilda. I wonder if this is some drug we gave her, or... This...")
	expr('NOEMI', 'happy')
	speak('NOEMI', "This is a dream isn't it?")
	speak('ARIEL', "No. I'm awake, anyway. Need me to slap you?")
	expr('NOEMI', nil)
	speak('NOEMI', "Please don't wake me up. The dream me is coding the new Recurse prototype right now. I'm working on face recognition.")
	speak('ARIEL', "You're very hard to understand, you know. What's the me in your dream doing?")
	speak('NOEMI', "Hm hm... You're trying to slap me awake, but I don't wake up.")
	expr('NOEMI', 'happy')
	speak('NOEMI', "Maybe you should try slapping Ratilda.")
	speak('ARIEL', "I'm not slapping your rat, Noemi. You do that.")
	expr('NOEMI', nil)
	speak('NOEMI', "Oh, um, Ariel, I meant to mention...")
	exit('NOEMI')
	wipe()
	wait(.8)
	enter('NOEMI', 'b')
	speak('NOEMI', "What did you really dream, earlier today? When you mirrored to me.")
	speak('ARIEL', "It was the story from Sumi. There were the two goats, and the - ")
	speak('NOEMI', "There was someone else there. A person. I didn't tell anyone else I saw them. I figured you didn't mean to put them there.")
	speak('ARIEL', "I didn't see anyone.")
	speak('NOEMI', "There was a person there. They... looked like you.")
	speak('NOEMI', "That's how I knew you didn't dream them on purpose. You can never see your own face in a dream.")
	speak('NOEMI', "But I saw you. Or someone who looked a lot like you, sitting crosslegged on top of that mountain.")
	speak('ARIEL', "You must've confused my dream with your own.")
	exit('NOEMI')
	enter('NOEMI', 'c')
	speak('NOEMI', "Ariel... I've relived hundreds of dreams, collages from Chris, lucid dreams from you, fragments from Braulio's prototype editor...")
	expr('NOEMI', 'shock')
	speak('NOEMI', "My perception is near perfect.")
	expr('NOEMI', nil)
	speak('ARIEL', "And I've recorded how many lucid dreams now?")
	speak('ARIEL', "You know me. I can't dream normally. I can't let my mind run wild. I don't slip and I can't afford mistakes.")
	speak('NOEMI', "A bug then... Recurse error. I'll look for a bug.")
	expr('NOEMI', 'happy')
	speak('NOEMI', "I can see the facial recognition code now. I'm refactoring. Maybe I'll fix it in the next Recurse.")
	expr('NOEMI', nil)
	speak('NOEMI', "But you should be careful. If you can't control your dreams...")
	speak('ARIEL', "Thanks for the warning, Noemi. And I'm glad you still had sense enough not to tell Sumi or Braulio that anything felt wrong.")
	speak('ARIEL', "You should really wake up sometime, though. I worry about you. And I miss talking to you normally, when your consciousness isn't somewhere else hacking away at a computer.")
	speak('NOEMI', "I miss you too, sometimes, Ariel. But then I replay one of your dreams from Recurse, and we talk for hours, just you and me, like when we were kids.")
	speak('ARIEL', "I'm going to get back to work. I hope Ratilda shapes up.")
	speak('NOEMI', "Ratilda appreciates the thought. Take care, Ariel.")
else
	speak('ARIEL', "Noemi is holding one of the rats, but neither are moving.")
	speak('NOEMI', "I guess her attention is elsewhere.")
end

setSwitch('pt1_09c', true)
