rotateTo('chair')
setSwitch('sumi_last_gazer')
wait(1)

speak('ARIEL', "This is our prototype. We call it 'gazer'.")
enterNVL()
enter('SUMI', 'c')
speak('SUMI', "Fascinating. The monitors then... You're able to see the dream as it's being played?")
speak('ARIEL', "Not quite. It's impossible to present a dream as a video because a dream is much more abstract. It's a collection of thoughts, visions, emotions, and ideas.")
speak('ARIEL', "Rather than present a dream directly, we have a video sample bank that we match to the patient's brain signature. Noemi designed a pretty complex AI to do the wave matching.")
speak('ARIEL', "Basically, if you take in the combined sum of all the images, your brain will respond in roughly the same way as the dreamer's. It gives you an idea of what the patient is experiencing.")
speak('SUMI', "Ingenious.")
speak('ARIEL', "Braulio mentioned you wanted a demo. I can set that up, but... You'd need to take a small Bluepill dose.")
expr('SUMI', 'intense')
speak('SUMI', "Do I look like a little drug use would scare me off?")
speak('ARIEL', "I try not to judge by appearance.")
expr('SUMI', nil)
speak('SUMI', "Ahaha, you're funny. I like you.")
speak('SUMI', "Between you and me, this won't be the first time I've tried Bluepill. Now strap me in and show me what Recurse can do.")
wait(0.5)
exitNVL()
wait(0.5)

fade('black')
teleport('gazer', 'gazer_target', 'NORTH', true)
rotateTo('chair')
setSwitch('pt1_05c', true)
fade('normal')

--fadeOutBGM(2)
bootGazer(true)
--todo: bgm
wait(2)
fade('black')
wait(2)
fade('normal')
wait(1)
bootGazer(false)
wait(2)

enterNVL()
enter('SUMI', 'c')
speak('ARIEL', "All done. What did you think?")
speak('SUMI', "Frankly? I'm a little underwhelmed. What was that dream supposed to look like?")
speak('ARIEL', "That was, umm... Green No.5. Dr. Kowalski was the original dreamer. It's supposed to be a surreal forest, I think.")
speak('SUMI', "I suppose I did see that, but... I don't know why anyone would want to dream about a forest.")
speak('SUMI', "And who was the white-haired woman?")
speak('ARIEL', "A woman? There shouldn't be any other people in that dream.")
speak('SUMI', "She was speaking something foreign. Not English.")
speak('ARIEL', "That isn't possible. Dreams can't contain languages that the dreamer doesn't know.")
expr('SUMI', 'intense')
speak('SUMI', "Then maybe your friend Kowalski dreamt it in some language he knows but I don't.")
expr('SUMI', nil)
speak('SUMI', "Never mind. Thank you for the demo.")
speak('ARIEL', "Sorry about that. I'll check with Noemi later. It's probably some corruption in the Green No.5 data.")
exitNVL()

play('pt1_05_tourcheck')
