enterNVL()
enter('CHRIS', 'b')

if not getSwitch('pt1_05a') then
	speak('ARIEL', "Sumi, I'd like you to meet Dr. Christian Kowalski. He's a former professor of chemistry at Aquila University and a pioneer in organic synthesis. Lucir is lucky to have him.")
	enter('SUMI', 'd')
	speak('CHRIS', "Pleased to meet you, Ms. Chey. Ariel always talks me up, but I'm not important here. I just look after the chemicals.")
	speak('ARIEL', "He's working on a way to use Recurser without the need for Bluepill. And he's a talented dream author.")
	speak('SUMI', "Ahh, Dr. Kowalski. The pleasure is mine.")
	speak('CHRIS', "It's easier to call me Chris.")
	speak('SUMI', "Ahaha, but Dr. Kowalski, you went through all that trouble to earn the degree, so it'd be disrespectful of me not to use the full title.")
	speak('CHRIS', "Really - ")
	expr('SUMI', 'intense')
	speak('SUMI', "I've heard of you, you know, Dr. Kowalski. They say you were the first to synthesize Bluepill.")
	expr('SUMI', nil)
	expr('CHRIS', 'pain')
	speak('CHRIS', "I'm not particularly proud of that.")
	expr('SUMI', 'intense')
	speak('SUMI', "Too much pride is a bad thing, but too much humility isn't attractive either. Sometimes if you're working at a startup, you need a taste for blood. Wouldn't you agree, Dr. Kowalski?")
	speak('CHRIS', "I...")
	expr('SUMI', nil)
	speak('SUMI', "Ahaha, I'm just joking. It really is a pleasure to meet you, Chris.")
	expr('CHRIS', nil)
	speak('CHRIS', "You have an interesting sense of humor.")
	speak('SUMI', "But really, I admire your work. Your area of research fascinates me. What makes you want to distance yourself from Bluepill?")
	speak('CHRIS', "My answer is a little complicated. But... You're aware that in most of the old Eastern Bloc countries, Bluepill still isn't a controlled substance?")
	speak('SUMI', "I might be aware. It seems to be becoming a popular street drug.")
	speak('CHRIS', "A drug that introduces a dreamlike suggestability... The potential for abuse is high. I don't think any scientist would be too happy about that.")
	speak('SUMI', "Maybe not. But an accomplishment is an accomplishment.")
	wait(0.5)
	expr('CHRIS', 'thinking')
	wait(0.5)
	speak('CHRIS', "I'm sorry if you've already gone over this with Braulio, but, what exactly is your interest in Lucir, Ms. Chey?")
	expr('CHRIS', nil)
	speak('CHRIS', "You seem very knowledgable about Bluepill, but we're trying to remove it from our product completely. We're not researching it. Bluepill and I are not important to the future of Recurser.")
	speak('SUMI', "My interest is purely financial.")
	speak('SUMI', "Lucir may be poised on the verge of a breakthrough, and there's a potential for a huge return on my investment, if what Braulio promises is the truth.")
	expr('CHRIS', 'thinking')
	speak('CHRIS', "Only money? That's a bit mundane, but I suppose better than some alternatives.")
	expr('CHRIS', nil)
	speak('CHRIS', "Well don't let me hold up the tour, Ariel. I've a few more items to take care of in the lab today anyway.")
	speak('SUMI', "Hope to see you around, Dr. Kowalski.")
else
	speak('CHRIS', "If Braulio comes looking for me, I'll be in the chemistry lab downstairs.")
end

setSwitch('pt1_05a', true)
play('pt1_05_tourcheck')
exitNVL()
