teleport('Gazer', 'chair', 'SOUTH', true)
fade('normal')
wait(1)
rotateTo('braulio_2')
wait(.6)

enterNVL()
enter('BRAULIO', 'b')
speak('BRAULIO', "Oh hey Ariel. You're awake?")
speak('ARIEL', "Yeah... How long was I out? Where is everyone?")
speak('BRAULIO', "Only an hour or two. But Noemi was able to perceive your dream just fine. It was my goat story, right?")
speak('ARIEL', "Sorry. It's what Sumi gave me.")
speak('BRAULIO', "Weird. But, once the lawyers clear everything on her end, we'll finally have funding. I'd want to throw a party if there wasn't so much work to get to, haha.")
speak('ARIEL', "That's a relief.")
speak('BRAULIO', "I'm going to make sure Sumi has everything she needs in the empty office downstairs. Feel free to take it easy for the rest of the day -- you've done a bunch already.")
expr('BRAULIO', 'unsure')
speak('BRAULIO', "...And thanks again for showing Sumi around. I love that she's helping us out, but something about her...")
expr('BRAULIO', 'determined')
speak('BRAULIO', "Never mind! Catch me in the office if you need anything!")
exitNVL()

teleport('F2', 'gazer', 'NORTH')
