enterNVL()
enter('BRAULIO', 'e')
speak('BRAULIO', "Hey! Listen up guys because you won't believe this! She's actually here, in person!")
enter('CHRIS', 'a', 'thinking')
enter('NOEMI', 'b')
speak('CHRIS', "Our mystery investor?")
speak('BRAULIO', "Yes! I didn't even know until yesterday that her group was interested, but she's in the meeting room now, and - ")
speak('BRAULIO', "Wait, Ariel, are you okay? You're shaking.")
speak('ARIEL', "It's nothing.")
speak('BRAULIO', "Okay, good, I'm glad you're okay, because she's looking to meet all of us. Like, right now.")
exitNVL()

teleport('Meeting', 'target', 'NORTH')
setSwitch('pt1_03', true)
play('pt1_04')
