
speak('ARIEL', "I feel bad poking around Chris's office, but... I'm worried about him.")
speak('ARIEL', "There are dates in here, and a lot of illustrations and sentence fragments. A diary?")
speak('ARIEL', "June 9th... Teeth fell out again.")
speak('ARIEL', "June 11th... Back in Ward No.9. Lucid, but still couldn't talk to any of the kids.")
speak('ARIEL', "June 12th... Another forest. Save for Gazer.")
speak('ARIEL', "June 15th... I die. There's a sense of relief. Can finally talk to the kids.")
wipe()
wait(0.5)
speak('ARIEL', "It's a dream journal, then. There are tons of discs in the back, too, like we'd feed into Gazer.")
speak('ARIEL', "I guess he recorded every dream he's ever had, and then handed us the good ones to use with Gazer.")
speak('ARIEL', "...The rest of these, though, are pretty dark.")
setSwitch('got_diary', true)
play('finale_gather_all')
