enterNVL()
speak('ARIEL', "I'm at the door, Noemi. It's Ariel.")
enter('NOEMI', 'c')
speak('ARIEL', "What's with the needle?")
speak('NOEMI', "Oh... I think it might be time to say goodbye to Ratricia and Rathilda.")
speak('ARIEL', "I suppose euthanasia is probably better than whatever's going on in their little brains.")
speak('NOEMI', "No. Rathilda woke up again. She kept slamming into the side of the cage. I think if I left her awake... she'd die quite quickly.")
speak('ARIEL', "I'm sorry to hear it.")
speak('NOEMI', "Ratthew has it too now. He won't wake up.")
speak('ARIEL', "We need to figure out what's happening to the rats. But, sorry, something else has come up as well. Have you heard of oneirophrenia?")
speak('NOEMI', "Hm hm. I think you showed me your report on it.")
speak('ARIEL', "I don't think so.")
speak('NOEMI', "Oh. Of course not. If I read it, it must've been the dream me.")
speak('ARIEL', "When was this? Last week? Last month? I'm trying to - ")
enter('BRAULIO', 'a', 'angry')
speak('BRAULIO', "Ariel! Noemi!")
speak('ARIEL', "Slow down. What's going on?")
speak('BRAULIO', "It's Sumi! She broke into the chemistry lab and swallowed... I don't even know. It was a lot. I think she's in a coma.")
expr('NOEMI', 'shock')
speak('ARIEL', "Bluepill?")
speak('BRAULIO', "No, just, everything! Was she trying to poison herself?")
expr('BRAULIO', 'determined')
expr('NOEMI', nil)
speak('BRAULIO', "I called an ambulance. I don't know what's going on any more. I'm going to try and bring her down to the lobby but she's barely moving.")
speak('BRAULIO', "If the EMTs come up here, tell them to go back down. I'll call you as soon as I know anything!")
exit('BRAULIO')
wipe()
wait(.7)
speak('NOEMI', "Was that... Braulio?")
speak('ARIEL', "Yes. It sounds like something terrible's happened to Sumi.")
speak('NOEMI', "I caught that much.")
speak('ARIEL', "I'm going to take this time to poke around the office. I think I'm on the verge of remembering something important, but... I just can't place it.")
speak('NOEMI', "It's a familiar feeling.")
expr('NOEMI', 'happy')
speak('NOEMI', "I'll be here if you need anything. You seem not yourself today, so let me help you if I can.")
exitNVL()

fade('black')
teleport('F2', 'noemi', 'WEST')
setSwitch('pt2_08', true)
fade('normal')
