setSwitch("midnight_over", true)
setSwitch("pt1_done", true)
setSwitch("pt1_13", true)
setSwitch("nightmare_go", false)
setSwitch("swap_floor", false)
enterNVL()

setWake(1)
wait(1)
speak('ARIEL', "AH!! Ha... Ha.")
wipe()
wait(1)
setWake(2)
wait(1)
speak('ARIEL', "Hah.")
wait(1)
setWake(-1)
enter('BRAULIO', 'b')
speak('BRAULIO', "You're awake!")
speak('ARIEL', "I'm awake. Back to normal. I hope.")
expr('BRAULIO', 'unsure')
speak('BRAULIO', "Um, do you remember today's date?")
speak('ARIEL', "Monday, March 1st. No, that's when I passed out. Is today Tuesday?")
enter('SUMI', 'd')
speak('SUMI', "The 2nd of March. Good.")
speak('BRAULIO', "And, um, your name. How about your name?")
speak('ARIEL', "It's Ariel.")
expr('BRAULIO', nil)
speak('BRAULIO', "Oh thank the lord.")
speak('SUMI', "Ahaha. You're okay. Welcome back to the waking world, Ariel.")
speak('ARIEL', "Sorry, what time is it? I get the feeling I've been out a while.")
speak('SUMI', "Almost 5:00 in the evening.")
speak('BRAULIO', "The Chey Group lawyers are all gone and we've signed the paperwork. I think you were asleep for that?")
speak('ARIEL', "Was I trying to record a dream?")
speak('BRAULIO', "Yeah! Sumi's going to try out mirroring.")
expr('SUMI', 'intense')
speak('SUMI', "About Dr. Kowalski...")
expr('BRAULIO', nil)
speak('BRAULIO', "Oh, um. I guess I should explain this. Chris is on leave for a little while.")
speak('ARIEL', "How long?")
speak('BRAULIO', "He wanted some rest. He's in a good place. I think... Um...")
speak('SUMI', "He'll be in touch.")
expr('SUMI', nil)
speak('SUMI', "Ariel, in the meantime, is the dream is finished? I'll be able to view it?")
speak('ARIEL', "Sorry, a mirroring demo? I don't remember today at all. Whatever I was just dreaming about, you definitely shouldn't view that.")
speak('BRAULIO', "Oh! Yeah Ariel you definitely should re-record.")
speak('ARIEL', "And you really want to try mirroring, Sumi? The Bluepill dose will be a lot higher. More than healthy.")
speak('SUMI', "I've signed a waiver and everything. Consider me your first customer.")
speak('ARIEL', "Only Noemi and I have tried this before. Where is Noemi anyway?")
speak('BRAULIO', "She's back in her lab, looking after the rats. Maybe, would it be a good idea, maybe you shouldn't talk to her for a while?")
speak('ARIEL', "I need to talk to her.")
speak('SUMI', "I'm sure it will be fine. Noemi is a special case.")
speak('BRAULIO', "Alright.")
speak('SUMI', "I have some calls to make anyway. Come grab me when you're ready to go.")
exitNVL()

fade('black')
setSwitch('pt2_01', true)
fade('normal')
