enterNVL()
enter('SUMI', 'c')
speak('ARIEL', "There you are. I had some trouble becoming lucid, but now I'm in control.")
speak('SUMI', "...")
speak('ARIEL', "Who are you then? Sumi? ...or Sumi?")
speak('SUMI', "...")
finaleCorridor()
speak('ARIEL', "It's useless holding a conversation in the dream world. My mind fills in both sides.")
exitNVL()

rotateTo('start')

wait(1.0)
speak('ARIEL', "Wait...")
speak('ARIEL', "No. Don't panic. I don't panic.")
speak('ARIEL', "I am the dreamer. I am the author. I am lucid and I am in control.")
speak('ARIEL', "Then why do I -- ")

rotateTo('sumi')
enterNVL()
enter('SUMI', 'c')
speak('SUMI', "You aren't me. You aren't me and you never will be.")
speak('SUMI', "You have cheated me, but you are out of time.")
expr('SUMI', 'intense')
killMonitors()
speak('SUMI', "____. IMPOSTER.")
exitNVL()
wait(1)

setWake(0)
play('pt2_07')